#!/bin/zsh
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
PROFILE="${1:-${BOT_RUNTIME_PROFILE:-sim}}"
QUIET="${2:-}"

case "$PROFILE" in
  sim|live) ;;
  *)
    echo "invalid runtime profile: $PROFILE (expected sim|live)" >&2
    return 2 2>/dev/null || exit 2
    ;;
esac

load_file() {
  local f="$1"
  [[ -f "$f" ]] || return 1
  set -a
  # shellcheck disable=SC1090
  source "$f"
  set +a
  return 0
}

LOADED_FILES=()

# Load root files first, then config files as overrides.
for candidate in \
  "$PROJECT_ROOT/.env" \
  "$PROJECT_ROOT/.env.$PROFILE" \
  "$PROJECT_ROOT/config/.env" \
  "$PROJECT_ROOT/config/.env.$PROFILE"; do
  if load_file "$candidate"; then
    LOADED_FILES+=("${candidate#$PROJECT_ROOT/}")
  fi
done

# Safe defaults and startup self-heal for empty symbol groups.
export BOT_RUNTIME_PROFILE="$PROFILE"
export MARKET_DATA_ONLY="${MARKET_DATA_ONLY:-1}"
export ALLOW_ORDER_EXECUTION="${ALLOW_ORDER_EXECUTION:-0}"
export DATA_BROKER="${DATA_BROKER:-schwab}"

export SHADOW_SYMBOLS_CORE="${SHADOW_SYMBOLS_CORE:-SPY,QQQ,DIA,IWM,MDY,VOO,VTI,RSP,AAPL,MSFT,NVDA,AMZN,GOOGL,META,AVGO,ORCL,CRM,ADBE,NFLX,DIS,WBD,GS,JPM,BKNG,ABNB,MAR,HLT}"
export SHADOW_SYMBOLS_VOLATILE="${SHADOW_SYMBOLS_VOLATILE:-SOXL,SOXS,TQQQ,SQQQ,MSTR,SMCI,COIN,TSLA,PLTR,AMD,MRVL,ARM,IBIT,ETHA,MARA,RIOT,UVXY,VIXY,AAL,UAL,DAL,LUV,ALK,JBLU,CCL,RCL,NCLH,EXPE,JETS,XOP,OIH,OXY,SLB,HAL}"
export SHADOW_SYMBOLS_DEFENSIVE="${SHADOW_SYMBOLS_DEFENSIVE:-TLT,GLD,XLV,XLU,XLP,MO,HYG,LQD,UUP,XLE,XLF,XLI,XLK,XLY,IEF,SHY,TIP,TLH,JNK,AGG,BND,MUB,IGIB,USHY,FLOT,VGIT,SCHD,VIG,DGRO,HDV,NOBL,VYM,DIVO,JEPI,JEPQ,SPLV,VTV,JNJ,PG,KO,PEP,MCD,ABBV,ABT,MRK,PFE,T,VZ,O,VICI,MAIN,XOM,CVX,COP,EOG,MPC,PSX,VLO,KMI,ITA,LMT,NOC,RTX,GD,LHX,LDOS}"
export SHADOW_SYMBOLS_COMMOD_FX_INTL="${SHADOW_SYMBOLS_COMMOD_FX_INTL:-DBC,UNG,CORN,SLV,USO,FXE,FXY,EFA,EEM,EWJ,FXI,VEA,VWO,IEFA,VGK,INDA,SMH,SOXX,VGT,IGV,XOP,OIH,JETS,VNQ,IYR}"

export DIVIDEND_SYMBOLS="${DIVIDEND_SYMBOLS:-SCHD,VIG,DGRO,HDV,NOBL,VYM,DIVO,JEPI,JEPQ,SPYD,DIV,FDVV,SCHY,JNJ,PG,KO,PEP,MCD,MO,ABBV,ABT,MRK,PFE,T,VZ,O,VICI,MAIN,XOM,CVX,COP,KMI,MPC,PSX,VLO,EOG,SLB}"
export DIVIDEND_QUALITY_SYMBOLS="${DIVIDEND_QUALITY_SYMBOLS:-SCHD,VIG,DGRO,HDV,NOBL,VYM,DIVO,SCHY,JNJ,PG,KO,PEP,MCD,ABBV,ABT,MRK,XOM,CVX,COP,O,VICI,MSFT,AAPL}"
export BOND_SYMBOLS="${BOND_SYMBOLS:-TLT,IEF,SHY,TIP,LQD,HYG}"

export COINBASE_WATCH_SYMBOLS="${COINBASE_WATCH_SYMBOLS:-BTC-USD,ETH-USD,SOL-USD,AVAX-USD,LTC-USD,LINK-USD,DOGE-USD}"
export COINBASE_WATCH_INTERVAL_SECONDS="${COINBASE_WATCH_INTERVAL_SECONDS:-20}"

if [[ "$QUIET" != "--quiet" ]]; then
  loaded="none"
  if (( ${#LOADED_FILES[@]} > 0 )); then
    loaded="${(j:,:)LOADED_FILES}"
  fi
  echo "runtime_env_loaded profile=$PROFILE files=$loaded"
fi
