#!/bin/zsh
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
PROFILE="${1:-${BOT_RUNTIME_PROFILE:-sim}}"
QUIET="${2:-}"

case "$PROFILE" in
  sim|live) ;;
  *)
    echo "invalid runtime profile: $PROFILE (expected sim|live)" >&2
    return 2 2>/dev/null || exit 2
    ;;
esac

load_file() {
  local f="$1"
  [[ -f "$f" ]] || return 1
  set -a
  # shellcheck disable=SC1090
  source "$f"
  set +a
  return 0
}

local_queue_db_default_path() {
  local local_root="${BOT_CHANNEL_QUEUE_LOCAL_ROOT:-$PROJECT_ROOT/local_fallback_storage}"
  printf '%s\n' "${local_root%/}/data/bot_channel_queue.sqlite3"
}

routed_queue_db_default_path() {
  printf '%s\n' "$PROJECT_ROOT/data/bot_channel_queue.sqlite3"
}

default_queue_db_path() {
  local prefer_local_raw="${BOT_CHANNEL_QUEUE_PREFER_LOCAL:-}"
  if [[ -n "$prefer_local_raw" ]]; then
    case "${prefer_local_raw:l}" in
      1|true|yes|on)
        local_queue_db_default_path
        return 0
        ;;
      *)
        routed_queue_db_default_path
        return 0
        ;;
    esac
  fi

  case "${BOT_LOGS_PREFER_EXTERNAL:-1:l}" in
    0|false|no|off)
      local_queue_db_default_path
      ;;
    *)
      routed_queue_db_default_path
      ;;
  esac
}

LOADED_FILES=()

# Load root files first, then config files as overrides.
for candidate in \
  "$PROJECT_ROOT/.env" \
  "$PROJECT_ROOT/.env.$PROFILE" \
  "$PROJECT_ROOT/.env.secrets.local" \
  "$PROJECT_ROOT/.env.$PROFILE.secrets.local" \
  "$PROJECT_ROOT/config/.env" \
  "$PROJECT_ROOT/config/.env.$PROFILE" \
  "$PROJECT_ROOT/config/.env.secrets.local" \
  "$PROJECT_ROOT/config/.env.$PROFILE.secrets.local" \
  "$PROJECT_ROOT/config/.env.access_mode_override" \
  "$PROJECT_ROOT/config/.env.apple_silicon_override" \
  "$PROJECT_ROOT/config/.env.host_profile_override" \
  "$PROJECT_ROOT/config/.env.memory_efficiency_override" \
  "$PROJECT_ROOT/config/.env.runtime_resource_guard_override" \
  "$PROJECT_ROOT/config/.env.pressure_relief_override" \
  "$PROJECT_ROOT/config/.env.guard_intelligence_override" \
  "$PROJECT_ROOT/config/.env.process_fanout_guard_override" \
  "$PROJECT_ROOT/config/.env.super_intelligence_override" \
  "$PROJECT_ROOT/config/.env.platform_intelligence_override" \
  "$PROJECT_ROOT/config/.env.platform_brain_v4_override" \
  "$PROJECT_ROOT/config/.env.platform_brain_v5_override" \
  "$PROJECT_ROOT/config/.env.platform_brain_v6_override" \
  "$PROJECT_ROOT/config/.env.frontier_intelligence_override" \
  "$PROJECT_ROOT/config/.env.platform_stabilization_quality_override" \
  "$PROJECT_ROOT/config/.env.platform_settlement_stabilization_override" \
  "$PROJECT_ROOT/config/.env.sleeve_ticker_universe_override" \
  "$PROJECT_ROOT/config/.env.paper_live_data_standard_override" \
  "$PROJECT_ROOT/config/.env.paper_400_ramp_override" \
  "$PROJECT_ROOT/config/.env.swap_pressure_override" \
  "$PROJECT_ROOT/config/.env.browser_quiet_override" \
  "$PROJECT_ROOT/config/.env.storage_pressure_override" \
  "$PROJECT_ROOT/config/.env.storage_target_override" \
  "$PROJECT_ROOT/config/.env.storage_override" \
  "$PROJECT_ROOT/config/.env.computer_task_override" \
  "$PROJECT_ROOT/config/.env.memory_pressure_intelligence_override" \
  "$PROJECT_ROOT/config/.env.autonomic_resource_governor_override" \
  "$PROJECT_ROOT/config/.env.operator_mode_override"; do
  if load_file "$candidate"; then
    LOADED_FILES+=("${candidate#$PROJECT_ROOT/}")
  fi
done

secret_placeholder_or_empty() {
  local value="${1:-}"
  case "$value" in
    ""|"YOUR_KEY_HERE"|"YOUR_SECRET_HERE"|"YOUR_REAL_KEY"|"YOUR_REAL_SECRET"|"YOUR_REAL_CLIENT_ID"|"<real_key>"|"<real_secret>"|"<real_client_id>")
      return 0
      ;;
  esac
  return 1
}

read_keychain_secret() {
  local service="$1"
  [[ -n "$service" ]] || return 1
  /usr/bin/security find-generic-password \
    -a "${SCHWAB_KEYCHAIN_ACCOUNT:-${USER:-$(id -un)}}" \
    -s "$service" \
    -w 2>/dev/null || return 1
}

fill_secret_from_keychain() {
  local var_name="$1"
  local service="$2"
  local current="${(P)var_name:-}"
  if ! secret_placeholder_or_empty "$current"; then
    return 0
  fi
  local value
  value="$(read_keychain_secret "$service" || true)"
  if secret_placeholder_or_empty "$value"; then
    return 0
  fi
  export "$var_name=$value"
}

export SCHWAB_KEYCHAIN_FALLBACK_ENABLED="${SCHWAB_KEYCHAIN_FALLBACK_ENABLED:-1}"
export SCHWAB_API_KEY_KEYCHAIN_SERVICE="${SCHWAB_API_KEY_KEYCHAIN_SERVICE:-schwab_trading_bot/SCHWAB_API_KEY}"
export SCHWAB_SECRET_KEYCHAIN_SERVICE="${SCHWAB_SECRET_KEYCHAIN_SERVICE:-schwab_trading_bot/SCHWAB_SECRET}"
export SCHWAB_REDIRECT_KEYCHAIN_SERVICE="${SCHWAB_REDIRECT_KEYCHAIN_SERVICE:-schwab_trading_bot/SCHWAB_REDIRECT}"
if [[ "${SCHWAB_KEYCHAIN_FALLBACK_ENABLED:l}" != "0" && "${SCHWAB_KEYCHAIN_FALLBACK_ENABLED:l}" != "false" && "${SCHWAB_KEYCHAIN_FALLBACK_ENABLED:l}" != "no" && "${SCHWAB_KEYCHAIN_FALLBACK_ENABLED:l}" != "off" ]]; then
  fill_secret_from_keychain "SCHWAB_API_KEY" "$SCHWAB_API_KEY_KEYCHAIN_SERVICE"
  fill_secret_from_keychain "SCHWAB_SECRET" "$SCHWAB_SECRET_KEYCHAIN_SERVICE"
  fill_secret_from_keychain "SCHWAB_REDIRECT" "$SCHWAB_REDIRECT_KEYCHAIN_SERVICE"
fi

# Safe defaults and startup self-heal for empty symbol groups.
export BOT_RUNTIME_PROFILE="$PROFILE"
export BOT_LOGS_EXTERNAL_MOUNT="${BOT_LOGS_EXTERNAL_MOUNT:-/Volumes/BOT_LOGS}"
export BOT_LOGS_EXTERNAL_PROJECT_DIR="${BOT_LOGS_EXTERNAL_PROJECT_DIR:-schwab_trading_bot}"
export BOT_LOGS_EXTERNAL_MOUNT_CANDIDATES="${BOT_LOGS_EXTERNAL_MOUNT_CANDIDATES:-$BOT_LOGS_EXTERNAL_MOUNT}"
export BOT_LOGS_EXTERNAL_VOLUME_NAME="${BOT_LOGS_EXTERNAL_VOLUME_NAME:-BOT_LOGS}"
export MARKET_DATA_ONLY="${MARKET_DATA_ONLY:-1}"
export ALLOW_ORDER_EXECUTION="${ALLOW_ORDER_EXECUTION:-0}"
export DATA_BROKER="${DATA_BROKER:-schwab}"
export TOP_BOT_PAPER_TRADING_ENABLED="${TOP_BOT_PAPER_TRADING_ENABLED:-1}"
export TOP_BOT_PAPER_TRADING_OPTIONS_ENABLED="${TOP_BOT_PAPER_TRADING_OPTIONS_ENABLED:-1}"
export TOP_BOT_PAPER_TRADING_OPTIONS_PROFILES="${TOP_BOT_PAPER_TRADING_OPTIONS_PROFILES:-default,aggressive,intraday_aggressive,swing_aggressive,options_on_futures,options_on_futures_aggressive}"
export PAPER_MIRROR_ALL_ACTIVE_SUB_BOTS="${PAPER_MIRROR_ALL_ACTIVE_SUB_BOTS:-0}"
export PAPER_BROKER_BRIDGE_ENABLED="${PAPER_BROKER_BRIDGE_ENABLED:-1}"
export PAPER_BROKER_BRIDGE_MODE="${PAPER_BROKER_BRIDGE_MODE:-jsonl}"
export LOG_SUB_BOT_DECISIONS="${LOG_SUB_BOT_DECISIONS:-1}"
export LOG_MASTER_VARIANT_DECISIONS="${LOG_MASTER_VARIANT_DECISIONS:-1}"
export LOG_GRAND_MASTER_DECISIONS="${LOG_GRAND_MASTER_DECISIONS:-1}"
export LOG_OPTIONS_MASTER_DECISIONS="${LOG_OPTIONS_MASTER_DECISIONS:-1}"
export LOG_FUTURES_MASTER_DECISIONS="${LOG_FUTURES_MASTER_DECISIONS:-1}"
export PREMARKET_TOKEN_MIN_EXPIRES_SECONDS="${PREMARKET_TOKEN_MIN_EXPIRES_SECONDS:-600}"
export PREMARKET_TOKEN_CHECK_INTERVAL_SECONDS="${PREMARKET_TOKEN_CHECK_INTERVAL_SECONDS:-600}"
export SCHWAB_AUTH_MIN_EXPIRES_SECONDS="${SCHWAB_AUTH_MIN_EXPIRES_SECONDS:-$PREMARKET_TOKEN_MIN_EXPIRES_SECONDS}"
export SCHWAB_AUTH_LEASE_MIN_SECONDS="${SCHWAB_AUTH_LEASE_MIN_SECONDS:-1200}"
export SCHWAB_AUTH_LEASE_CRITICAL_SECONDS="${SCHWAB_AUTH_LEASE_CRITICAL_SECONDS:-600}"
export SCHWAB_INTERACTIVE_FORCE_MAX_TOKEN_AGE_SECONDS="${SCHWAB_INTERACTIVE_FORCE_MAX_TOKEN_AGE_SECONDS:-1}"

export SHADOW_SYMBOLS_CORE="${SHADOW_SYMBOLS_CORE:-SPY,QQQ,DIA,IWM,MDY,VOO,VTI,RSP,AAPL,MSFT,NVDA,AMZN,GOOGL,META,AVGO,ORCL,CRM,ADBE,NFLX,DIS,WBD,GS,JPM,BKNG,ABNB,MAR,HLT}"
export SHADOW_SYMBOLS_VOLATILE="${SHADOW_SYMBOLS_VOLATILE:-SOXL,SOXS,TQQQ,SQQQ,MSTR,SMCI,COIN,TSLA,PLTR,AMD,MRVL,ARM,IBIT,ETHA,MARA,RIOT,UVXY,VIXY,AAL,UAL,DAL,LUV,ALK,JBLU,CCL,RCL,NCLH,EXPE,JETS,XOP,OIH,OXY,SLB,HAL}"
export SHADOW_SYMBOLS_DEFENSIVE="${SHADOW_SYMBOLS_DEFENSIVE:-TLT,GLD,XLV,XLU,XLP,MO,HYG,LQD,UUP,XLE,XLF,XLI,XLK,XLY,IEF,SHY,TIP,TLH,JNK,AGG,BND,MUB,IGIB,USHY,FLOT,VGIT,SCHD,VIG,DGRO,HDV,NOBL,VYM,DIVO,JEPI,JEPQ,SPLV,VTV,JNJ,PG,KO,PEP,MCD,ABBV,ABT,MRK,PFE,T,VZ,O,VICI,MAIN,XOM,CVX,COP,EOG,MPC,PSX,VLO,KMI,ITA,LMT,NOC,RTX,GD,LHX,LDOS}"
export SHADOW_SYMBOLS_COMMOD_FX_INTL="${SHADOW_SYMBOLS_COMMOD_FX_INTL:-DBC,UNG,CORN,SLV,USO,FXE,FXY,EFA,EEM,EWJ,FXI,VEA,VWO,IEFA,VGK,INDA,SMH,SOXX,VGT,IGV,XOP,OIH,JETS,VNQ,IYR}"

export DIVIDEND_SYMBOLS="${DIVIDEND_SYMBOLS:-SCHD,VIG,DGRO,HDV,NOBL,VYM,DIVO,JEPI,JEPQ,SPYD,DIV,FDVV,SCHY,JNJ,PG,KO,PEP,MCD,MO,ABBV,ABT,MRK,PFE,T,VZ,O,VICI,MAIN,XOM,CVX,COP,KMI,MPC,PSX,VLO,EOG,SLB}"
export DIVIDEND_QUALITY_SYMBOLS="${DIVIDEND_QUALITY_SYMBOLS:-SCHD,VIG,DGRO,HDV,NOBL,VYM,DIVO,SCHY,JNJ,PG,KO,PEP,MCD,ABBV,ABT,MRK,XOM,CVX,COP,O,VICI,MSFT,AAPL}"
export DIVIDEND_DRIP_LOOKBACK_DAYS="${DIVIDEND_DRIP_LOOKBACK_DAYS:-400}"
export DIVIDEND_DRIP_RECENT_WINDOW_DAYS="${DIVIDEND_DRIP_RECENT_WINDOW_DAYS:-180}"
export DIVIDEND_DRIP_SYNC_ON_START="${DIVIDEND_DRIP_SYNC_ON_START:-1}"
export DIVIDEND_DRIP_AUTO_REFRESH_ENABLED="${DIVIDEND_DRIP_AUTO_REFRESH_ENABLED:-1}"
export DIVIDEND_DRIP_MAX_STALE_SECONDS="${DIVIDEND_DRIP_MAX_STALE_SECONDS:-21600}"
export DIVIDEND_DRIP_REFRESH_COOLDOWN_SECONDS="${DIVIDEND_DRIP_REFRESH_COOLDOWN_SECONDS:-1800}"
export BOND_SYMBOLS="${BOND_SYMBOLS:-TLT,IEF,TLH,VGIT,VGLT,EDV,ZROZ,SHY,FLOT,VGSH,SCHO,TIP,VTIP,SCHP,LQD,IGIB,HYG,JNK,USHY,AGG,BND,MUB}"
export BOND_CONTEXT_SYMBOLS="${BOND_CONTEXT_SYMBOLS:-UUP,GLD,SPY,TLT,IEF,TLH,VGIT,SHY,TIP,VTIP,SCHP,LQD,IGIB,HYG,JNK,USHY,AGG,BND,MUB,XLU,XLF,XLE,VIXY,DBC,USO}"
export MARKET_MICRO_LOOKBACK_DAYS="${MARKET_MICRO_LOOKBACK_DAYS:-21}"
export MARKET_MICRO_FINRA_LOOKBACK_DAYS="${MARKET_MICRO_FINRA_LOOKBACK_DAYS:-15}"
export MARKET_MICRO_SYMBOLS="${MARKET_MICRO_SYMBOLS:-$SHADOW_SYMBOLS_CORE,$SHADOW_SYMBOLS_VOLATILE,$SHADOW_SYMBOLS_DEFENSIVE,$SHADOW_SYMBOLS_COMMOD_FX_INTL,$BOND_SYMBOLS,$BOND_CONTEXT_SYMBOLS}"
export SEC_EDGAR_USER_AGENT="${SEC_EDGAR_USER_AGENT:-Daniel Kingsley dan_kingsley@aol.com}"
export SEC_EDGAR_SYMBOLS="${SEC_EDGAR_SYMBOLS:-$SHADOW_SYMBOLS_CORE,$SHADOW_SYMBOLS_VOLATILE,$DIVIDEND_QUALITY_SYMBOLS}"
export EXTENDED_QUANT_SYMBOLS="${EXTENDED_QUANT_SYMBOLS:-$SHADOW_SYMBOLS_CORE,$SHADOW_SYMBOLS_VOLATILE,$SHADOW_SYMBOLS_DEFENSIVE,$BOND_SYMBOLS,$BOND_CONTEXT_SYMBOLS}"
export TASTYTRADE_USER_AGENT="${TASTYTRADE_USER_AGENT:-schwab-trading-bot/1.0}"
export TASTYTRADE_CLIENT_ID="${TASTYTRADE_CLIENT_ID:-${TASTYTRADE_API_KEY:-}}"
export TASTYTRADE_LOGIN="${TASTYTRADE_LOGIN:-}"
export TASTYTRADE_PASSWORD="${TASTYTRADE_PASSWORD:-}"
export TASTYTRADE_SYMBOLS="${TASTYTRADE_SYMBOLS:-SPY,QQQ}"
export TASTYTRADE_SANDBOX="${TASTYTRADE_SANDBOX:-0}"
export TASTYTRADE_ALLOW_LIVE_PROFILE_SANDBOX="${TASTYTRADE_ALLOW_LIVE_PROFILE_SANDBOX:-0}"
export TASTYTRADE_TIMEOUT_SECONDS="${TASTYTRADE_TIMEOUT_SECONDS:-12}"
export TASTYTRADE_SCHWAB_ALIGNMENT_HOURS="${TASTYTRADE_SCHWAB_ALIGNMENT_HOURS:-6}"
export TASTYTRADE_MAX_SCHWAB_REL_SPREAD="${TASTYTRADE_MAX_SCHWAB_REL_SPREAD:-0.05}"
export TASTYTRADE_SCHWAB_TOLERANCE_MINUTES="${TASTYTRADE_SCHWAB_TOLERANCE_MINUTES:-25}"
export TASTYTRADE_SCHWAB_ALIGNMENT_MAX_BYTES="${TASTYTRADE_SCHWAB_ALIGNMENT_MAX_BYTES:-8388608}"
export OPTIONS_FLOW_SYMBOLS="${OPTIONS_FLOW_SYMBOLS:-${TASTYTRADE_SYMBOLS:-}}"
export OPTIONS_FLOW_TIMEOUT_SECONDS="${OPTIONS_FLOW_TIMEOUT_SECONDS:-20}"
export OPTIONS_FLOW_POLYGON_CONTRACT_LIMIT="${OPTIONS_FLOW_POLYGON_CONTRACT_LIMIT:-250}"
export UNUSUAL_WHALES_EXPORT_PATH="${UNUSUAL_WHALES_EXPORT_PATH:-}"
export UNUSUAL_WHALES_EXPORT_MAX_AGE_SECONDS="${UNUSUAL_WHALES_EXPORT_MAX_AGE_SECONDS:-21600}"
export UNUSUAL_WHALES_EXPORT_MIN_STABLE_SECONDS="${UNUSUAL_WHALES_EXPORT_MIN_STABLE_SECONDS:-30}"
export OPTIONS_FLOW_REFRESH_INTERVAL_SECONDS="${OPTIONS_FLOW_REFRESH_INTERVAL_SECONDS:-3600}"
export OPTIONS_FLOW_EFFICIENCY_INTERVAL_SECONDS="${OPTIONS_FLOW_EFFICIENCY_INTERVAL_SECONDS:-600}"
export OPTIONS_FLOW_EFFICIENCY_TIMEOUT_SECONDS="${OPTIONS_FLOW_EFFICIENCY_TIMEOUT_SECONDS:-900}"
export OPTIONS_FLOW_MAX_STALE_SECONDS="${OPTIONS_FLOW_MAX_STALE_SECONDS:-14400}"
export OPTIONS_FLOW_REFRESH_COOLDOWN_SECONDS="${OPTIONS_FLOW_REFRESH_COOLDOWN_SECONDS:-1800}"
export STORAGE_BACKPRESSURE_AUTOPILOT_INTERVAL_SECONDS="${STORAGE_BACKPRESSURE_AUTOPILOT_INTERVAL_SECONDS:-300}"
export STORAGE_BACKPRESSURE_AUTOPILOT_POLL_SECONDS="${STORAGE_BACKPRESSURE_AUTOPILOT_POLL_SECONDS:-20}"
export STORAGE_BACKPRESSURE_AUTOPILOT_WAIT_TIMEOUT_SECONDS="${STORAGE_BACKPRESSURE_AUTOPILOT_WAIT_TIMEOUT_SECONDS:-900}"
export STORAGE_BACKPRESSURE_AUTOPILOT_TIMEOUT_SECONDS="${STORAGE_BACKPRESSURE_AUTOPILOT_TIMEOUT_SECONDS:-2400}"
export STORAGE_BACKPRESSURE_AUTOPILOT_BACKPRESSURE_TIMEOUT_SECONDS="${STORAGE_BACKPRESSURE_AUTOPILOT_BACKPRESSURE_TIMEOUT_SECONDS:-900}"
export STORAGE_PRESSURE_CLEARANCE_INTERVAL_SECONDS="${STORAGE_PRESSURE_CLEARANCE_INTERVAL_SECONDS:-180}"
export STORAGE_PRESSURE_CLEARANCE_CHECKPOINT_MODE="${STORAGE_PRESSURE_CLEARANCE_CHECKPOINT_MODE:-passive}"
export STORAGE_PRESSURE_CLEARANCE_MAX_CYCLES="${STORAGE_PRESSURE_CLEARANCE_MAX_CYCLES:-1}"
export STORAGE_PRESSURE_CLEARANCE_POLL_SECONDS="${STORAGE_PRESSURE_CLEARANCE_POLL_SECONDS:-10}"
export STORAGE_PRESSURE_CLEARANCE_WAIT_TIMEOUT_SECONDS="${STORAGE_PRESSURE_CLEARANCE_WAIT_TIMEOUT_SECONDS:-180}"
export STORAGE_PRESSURE_CLEARANCE_TIMEOUT_SECONDS="${STORAGE_PRESSURE_CLEARANCE_TIMEOUT_SECONDS:-900}"
export SQL_LINK_SERVICE_MAINTENANCE_LOCK_POLL_SECONDS="${SQL_LINK_SERVICE_MAINTENANCE_LOCK_POLL_SECONDS:-5}"
export SQL_LINK_SERVICE_MAINTENANCE_LOCK_WAIT_SECONDS="${SQL_LINK_SERVICE_MAINTENANCE_LOCK_WAIT_SECONDS:-900}"
export SQL_LINK_SERVICE_SHARD_EXPLANATIONS_HOT_RETENTION_HOT_HOURS="${SQL_LINK_SERVICE_SHARD_EXPLANATIONS_HOT_RETENTION_HOT_HOURS:-0}"
export SQL_LINK_SERVICE_SHARD_EXPLANATIONS_HOT_RETENTION_MAX_ROWS="${SQL_LINK_SERVICE_SHARD_EXPLANATIONS_HOT_RETENTION_MAX_ROWS:-300000}"
export SQL_LINK_SERVICE_SHARD_CRYPTO_EXPLANATIONS_HOT_RETENTION_HOT_HOURS="${SQL_LINK_SERVICE_SHARD_CRYPTO_EXPLANATIONS_HOT_RETENTION_HOT_HOURS:-0}"
export SQL_LINK_SERVICE_SHARD_CRYPTO_EXPLANATIONS_HOT_RETENTION_MAX_ROWS="${SQL_LINK_SERVICE_SHARD_CRYPTO_EXPLANATIONS_HOT_RETENTION_MAX_ROWS:-250000}"
export SQL_LINK_SERVICE_SHARD_SHADOW_ATTRIBUTION_HOT_RETENTION_HOT_HOURS="${SQL_LINK_SERVICE_SHARD_SHADOW_ATTRIBUTION_HOT_RETENTION_HOT_HOURS:-0}"
export SQL_LINK_SERVICE_SHARD_SHADOW_ATTRIBUTION_HOT_RETENTION_MAX_ROWS="${SQL_LINK_SERVICE_SHARD_SHADOW_ATTRIBUTION_HOT_RETENTION_MAX_ROWS:-250000}"
export SQL_LINK_SERVICE_SHARD_CRYPTO_SHADOW_ATTRIBUTION_HOT_RETENTION_HOT_HOURS="${SQL_LINK_SERVICE_SHARD_CRYPTO_SHADOW_ATTRIBUTION_HOT_RETENTION_HOT_HOURS:-0}"
export SQL_LINK_SERVICE_SHARD_CRYPTO_SHADOW_ATTRIBUTION_HOT_RETENTION_MAX_ROWS="${SQL_LINK_SERVICE_SHARD_CRYPTO_SHADOW_ATTRIBUTION_HOT_RETENTION_MAX_ROWS:-250000}"
if [[ "$PROFILE" == "live" && "${TASTYTRADE_SANDBOX:-0}" == "1" && "${TASTYTRADE_ALLOW_LIVE_PROFILE_SANDBOX:-0}" != "1" ]]; then
  export TASTYTRADE_SANDBOX=0
fi
export SCHWAB_EDUCATION_CONTEXT_REFRESH_INTERVAL_SECONDS="${SCHWAB_EDUCATION_CONTEXT_REFRESH_INTERVAL_SECONDS:-3600}"
export SCHWAB_EDUCATION_CONTEXT_MAX_STALE_SECONDS="${SCHWAB_EDUCATION_CONTEXT_MAX_STALE_SECONDS:-14400}"
export SCHWAB_EDUCATION_CONTEXT_REFRESH_COOLDOWN_SECONDS="${SCHWAB_EDUCATION_CONTEXT_REFRESH_COOLDOWN_SECONDS:-1800}"

export COINBASE_WATCH_SYMBOLS="${COINBASE_WATCH_SYMBOLS:-BTC-USD,ETH-USD,SOL-USD,AVAX-USD,LTC-USD,LINK-USD,DOGE-USD}"
export COINBASE_CONTEXT_SYMBOLS="${COINBASE_CONTEXT_SYMBOLS:-BTC-USD,ETH-USD,SOL-USD,AVAX-USD,LTC-USD,LINK-USD,DOGE-USD}"
export COINBASE_WATCH_INTERVAL_SECONDS="${COINBASE_WATCH_INTERVAL_SECONDS:-20}"
export COINBASE_CACHE_MAX_ENTRIES="${COINBASE_CACHE_MAX_ENTRIES:-256}"
export COINBASE_WEBSOCKET_BOOK_DEPTH="${COINBASE_WEBSOCKET_BOOK_DEPTH:-10}"
export COINBASE_FUTURES_WATCH_SYMBOLS="${COINBASE_FUTURES_WATCH_SYMBOLS:-BTC-USD,ETH-USD,SOL-USD,AVAX-USD,LTC-USD,LINK-USD,DOGE-USD}"
export COINBASE_FUTURES_CONTEXT_SYMBOLS="${COINBASE_FUTURES_CONTEXT_SYMBOLS:-BTC-USD,ETH-USD,SOL-USD,AVAX-USD,LTC-USD,LINK-USD,DOGE-USD}"
export COINBASE_PROXY_CONTEXT_SYMBOLS="${COINBASE_PROXY_CONTEXT_SYMBOLS:-SPY,QQQ,TLT,UUP,GLD}"
export CRYPTO_MARKET_CONTEXT_SYMBOLS="${CRYPTO_MARKET_CONTEXT_SYMBOLS:-$COINBASE_WATCH_SYMBOLS,$COINBASE_FUTURES_WATCH_SYMBOLS}"
export CRYPTO_MARKET_CONTEXT_TIMEOUT_SECONDS="${CRYPTO_MARKET_CONTEXT_TIMEOUT_SECONDS:-12}"
export CRYPTO_MARKET_CONTEXT_MAX_REL_SPREAD="${CRYPTO_MARKET_CONTEXT_MAX_REL_SPREAD:-0.05}"
export CRYPTO_MARKET_CONTEXT_USER_AGENT="${CRYPTO_MARKET_CONTEXT_USER_AGENT:-Daniel Kingsley dan_kingsley@aol.com}"
export COINMETRICS_API_KEY="${COINMETRICS_API_KEY:-}"
export ETHERSCAN_API_KEY="${ETHERSCAN_API_KEY:-}"
export MARKET_CRYPTO_CORRELATION_AUTO_REFRESH_ENABLED="${MARKET_CRYPTO_CORRELATION_AUTO_REFRESH_ENABLED:-0}"
export MARKET_CRYPTO_CORRELATION_REFRESH_INTERVAL_SECONDS="${MARKET_CRYPTO_CORRELATION_REFRESH_INTERVAL_SECONDS:-300}"
export MARKET_CRYPTO_CORRELATION_MAX_STALE_SECONDS="${MARKET_CRYPTO_CORRELATION_MAX_STALE_SECONDS:-600}"
export MARKET_CRYPTO_CORRELATION_REFRESH_COOLDOWN_SECONDS="${MARKET_CRYPTO_CORRELATION_REFRESH_COOLDOWN_SECONDS:-120}"
export ONE_NUMBERS_REPORT_TIMEZONE="${ONE_NUMBERS_REPORT_TIMEZONE:-America/New_York}"
export ONE_NUMBERS_SESSION_AWARE_DATA_QUALITY="${ONE_NUMBERS_SESSION_AWARE_DATA_QUALITY:-1}"
export ONE_NUMBERS_SESSION_TIMEZONE="${ONE_NUMBERS_SESSION_TIMEZONE:-$ONE_NUMBERS_REPORT_TIMEZONE}"
export ONE_NUMBERS_SESSION_START="${ONE_NUMBERS_SESSION_START:-09:30}"
export ONE_NUMBERS_SESSION_END="${ONE_NUMBERS_SESSION_END:-16:00}"
export ONE_NUMBERS_DECISION_STALE_GRACE_SECONDS="${ONE_NUMBERS_DECISION_STALE_GRACE_SECONDS:-120}"
export ONE_NUMBERS_GOVERNANCE_STALE_GRACE_SECONDS="${ONE_NUMBERS_GOVERNANCE_STALE_GRACE_SECONDS:-180}"
export ONE_NUMBERS_OFF_HOURS_STALE_GRACE_SECONDS="${ONE_NUMBERS_OFF_HOURS_STALE_GRACE_SECONDS:-259200}"
export ONE_NUMBERS_REFRESH_INTERVAL_SECONDS="${ONE_NUMBERS_REFRESH_INTERVAL_SECONDS:-300}"
export ONE_NUMBERS_OFF_HOURS_REFRESH_INTERVAL_SECONDS="${ONE_NUMBERS_OFF_HOURS_REFRESH_INTERVAL_SECONDS:-3600}"
export ONE_NUMBERS_REFRESH_LAUNCHD_INTERVAL_SECONDS="${ONE_NUMBERS_REFRESH_LAUNCHD_INTERVAL_SECONDS:-180}"
export INGESTION_BACKPRESSURE_REFRESH_INTERVAL_SECONDS="${INGESTION_BACKPRESSURE_REFRESH_INTERVAL_SECONDS:-180}"
export DATA_SOURCE_DIVERGENCE_REFRESH_INTERVAL_SECONDS="${DATA_SOURCE_DIVERGENCE_REFRESH_INTERVAL_SECONDS:-300}"
export OPS_WATCHDOG_REFRESH_MAX_AGE_SECONDS="${OPS_WATCHDOG_REFRESH_MAX_AGE_SECONDS:-1800}"
export OPS_WATCHDOG_BACKPRESSURE_MAX_AGE_SECONDS="${OPS_WATCHDOG_BACKPRESSURE_MAX_AGE_SECONDS:-180}"
export OPS_WATCHDOG_DIVERGENCE_MAX_AGE_SECONDS="${OPS_WATCHDOG_DIVERGENCE_MAX_AGE_SECONDS:-300}"
export OPS_WATCHDOG_LAUNCHD_INTERVAL_SECONDS="${OPS_WATCHDOG_LAUNCHD_INTERVAL_SECONDS:-180}"
export SCHWAB_ACCOUNT_HASH_AUTO_DISCOVER="${SCHWAB_ACCOUNT_HASH_AUTO_DISCOVER:-1}"
export LIVE_ACCOUNTS_SNAPSHOT_ALLOW_GLOBAL_FALLBACK="${LIVE_ACCOUNTS_SNAPSHOT_ALLOW_GLOBAL_FALLBACK:-0}"
export BROKER_TRUTH_SHARED_SNAPSHOT_MAX_AGE_SECONDS="${BROKER_TRUTH_SHARED_SNAPSHOT_MAX_AGE_SECONDS:-15}"
export BROKER_TRUTH_SHARED_SNAPSHOT_LOCK_WAIT_SECONDS="${BROKER_TRUTH_SHARED_SNAPSHOT_LOCK_WAIT_SECONDS:-1.25}"
export BROKER_TRUTH_SHARED_SNAPSHOT_SKIP_WRITE_ON_LOCK_TIMEOUT="${BROKER_TRUTH_SHARED_SNAPSHOT_SKIP_WRITE_ON_LOCK_TIMEOUT:-1}"
export FX_SYMBOLS="${FX_SYMBOLS:-UUP,FXE,FXY,FXB,FXC,FXA,CYB,EUO,YCS,UDN}"
export FX_CONTEXT_SYMBOLS="${FX_CONTEXT_SYMBOLS:-SPY,QQQ,TLT,GLD,UUP,FXE,FXY,FXB,FXC,FXA}"
export FX_REALTIME_SYMBOLS="${FX_REALTIME_SYMBOLS:-EURUSD,USDJPY,GBPUSD,USDCHF,USDCAD,AUDUSD}"
export FX_REALTIME_CONTEXT_SYMBOLS="${FX_REALTIME_CONTEXT_SYMBOLS:-EURUSD,USDJPY}"
export FX_SHADOW_INTERVAL="${FX_SHADOW_INTERVAL:-45}"
export FX_SHADOW_MAX_ITERS="${FX_SHADOW_MAX_ITERS:-0}"
export FX_SHADOW_ENABLED="${FX_SHADOW_ENABLED:-1}"
export FX_OFF_HOURS_CONTEXT_ONLY="${FX_OFF_HOURS_CONTEXT_ONLY:-1}"
export FX_REALTIME_QUOTES_ENABLED="${FX_REALTIME_QUOTES_ENABLED:-1}"
export FX_SESSION_GATE_ENABLED="${FX_SESSION_GATE_ENABLED:-0}"
export FX_EVENT_LOCK_ENABLED="${FX_EVENT_LOCK_ENABLED:-0}"
export FX_EVENT_LOCK_WINDOWS_ET="${FX_EVENT_LOCK_WINDOWS_ET:-}"
export FX_OFF_HOURS_CONTEXT_SYNC_SECONDS="${FX_OFF_HOURS_CONTEXT_SYNC_SECONDS:-300}"
export FX_PROXY_SESSION_TIMEZONE="${FX_PROXY_SESSION_TIMEZONE:-America/New_York}"
export FX_PROXY_SESSION_START="${FX_PROXY_SESSION_START:-09:30}"
export FX_PROXY_SESSION_END="${FX_PROXY_SESSION_END:-16:00}"
export FX_PROXY_SESSION_ISO_WEEKDAYS="${FX_PROXY_SESSION_ISO_WEEKDAYS:-1,2,3,4,5}"
export FX_FOREX_SESSION_TIMEZONE="${FX_FOREX_SESSION_TIMEZONE:-America/New_York}"
export FX_FOREX_SESSION_WEEK_START="${FX_FOREX_SESSION_WEEK_START:-17:00}"
export FX_FOREX_SESSION_WEEK_END="${FX_FOREX_SESSION_WEEK_END:-17:00}"
export FX_MARKET_CONTEXT_TIMEOUT_SECONDS="${FX_MARKET_CONTEXT_TIMEOUT_SECONDS:-20}"
export FX_MARKET_CONTEXT_AUTO_REFRESH_ENABLED="${FX_MARKET_CONTEXT_AUTO_REFRESH_ENABLED:-1}"
export FX_MARKET_CONTEXT_REFRESH_INTERVAL_SECONDS="${FX_MARKET_CONTEXT_REFRESH_INTERVAL_SECONDS:-900}"
export FX_MARKET_CONTEXT_MAX_STALE_SECONDS="${FX_MARKET_CONTEXT_MAX_STALE_SECONDS:-1800}"
export FX_MARKET_CONTEXT_REFRESH_COOLDOWN_SECONDS="${FX_MARKET_CONTEXT_REFRESH_COOLDOWN_SECONDS:-300}"
export FX_MARKET_CONTEXT_TWELVE_DATA_ENABLED="${FX_MARKET_CONTEXT_TWELVE_DATA_ENABLED:-1}"
export FX_TWELVE_DATA_INTERVAL="${FX_TWELVE_DATA_INTERVAL:-5min}"
export FX_TWELVE_DATA_OUTPUTSIZE="${FX_TWELVE_DATA_OUTPUTSIZE:-72}"
export FX_TWELVE_DATA_REQUEST_TIMEOUT_SECONDS="${FX_TWELVE_DATA_REQUEST_TIMEOUT_SECONDS:-12}"
export FX_TWELVE_DATA_DEFAULT_SPREAD_BPS="${FX_TWELVE_DATA_DEFAULT_SPREAD_BPS:-6}"
export FX_TWELVE_DATA_CACHE_TTL_SECONDS="${FX_TWELVE_DATA_CACHE_TTL_SECONDS:-900}"
export FX_TWELVE_DATA_STALE_GRACE_SECONDS="${FX_TWELVE_DATA_STALE_GRACE_SECONDS:-1800}"
export FX_TWELVE_DATA_COOLDOWN_STALE_MAX_SECONDS="${FX_TWELVE_DATA_COOLDOWN_STALE_MAX_SECONDS:-21600}"
export FX_TWELVE_DATA_MAX_CREDITS_PER_MINUTE="${FX_TWELVE_DATA_MAX_CREDITS_PER_MINUTE:-8}"
export FX_TWELVE_DATA_CREDIT_RESERVE="${FX_TWELVE_DATA_CREDIT_RESERVE:-3}"
export FX_TWELVE_DATA_MAX_PAIRS_PER_RUN="${FX_TWELVE_DATA_MAX_PAIRS_PER_RUN:-2}"
export FX_TWELVE_DATA_RATE_LIMIT_COOLDOWN_SECONDS="${FX_TWELVE_DATA_RATE_LIMIT_COOLDOWN_SECONDS:-900}"
export FX_TWELVE_DATA_DAILY_QUOTA_RESET_HOUR_UTC="${FX_TWELVE_DATA_DAILY_QUOTA_RESET_HOUR_UTC:-0}"
export FX_TWELVE_DATA_DAILY_QUOTA_RESET_MINUTE_UTC="${FX_TWELVE_DATA_DAILY_QUOTA_RESET_MINUTE_UTC:-0}"
export FX_TWELVE_DATA_DAILY_QUOTA_RESET_GRACE_SECONDS="${FX_TWELVE_DATA_DAILY_QUOTA_RESET_GRACE_SECONDS:-300}"
export FX_MARKET_CONTEXT_ALPHA_VANTAGE_ENABLED="${FX_MARKET_CONTEXT_ALPHA_VANTAGE_ENABLED:-0}"
export TWELVE_DATA_API_KEY="${TWELVE_DATA_API_KEY:-}"
export ALPHA_VANTAGE_API_KEY="${ALPHA_VANTAGE_API_KEY:-}"
export FX_DIRECT_EXECUTION_ENABLED="${FX_DIRECT_EXECUTION_ENABLED:-0}"
export SCHWAB_FOREX_API_VERIFIED="${SCHWAB_FOREX_API_VERIFIED:-0}"
export SQL_LINK_SERVICE_INTERVAL_SECONDS="${SQL_LINK_SERVICE_INTERVAL_SECONDS:-60}"
export SQL_LINK_SERVICE_JSON_FILE_SYNC_MIN_INTERVAL_SECONDS="${SQL_LINK_SERVICE_JSON_FILE_SYNC_MIN_INTERVAL_SECONDS:-600}"
QUEUE_DB_DEFAULT_PATH="$(default_queue_db_path)"
export BOT_CHANNEL_QUEUE_DB="${BOT_CHANNEL_QUEUE_DB:-$QUEUE_DB_DEFAULT_PATH}"
export SQL_LINK_SERVICE_QUEUE_DB="${SQL_LINK_SERVICE_QUEUE_DB:-${BOT_CHANNEL_QUEUE_DB}}"
export SQL_LINK_SERVICE_QUEUE_PRUNE_ORPHANS="${SQL_LINK_SERVICE_QUEUE_PRUNE_ORPHANS:-1}"
export SQL_LINK_SERVICE_QUEUE_ORPHAN_DAYS="${SQL_LINK_SERVICE_QUEUE_ORPHAN_DAYS:-14}"
export SQL_LINK_SERVICE_QUEUE_MAX_DB_GB="${SQL_LINK_SERVICE_QUEUE_MAX_DB_GB:-12}"
export SQL_LINK_SERVICE_QUEUE_MAX_ROWS="${SQL_LINK_SERVICE_QUEUE_MAX_ROWS:-240000}"
export SQL_LINK_SERVICE_AUTO_LOCAL_FALLBACK_PRUNE="${SQL_LINK_SERVICE_AUTO_LOCAL_FALLBACK_PRUNE:-1}"
export SQL_LINK_SERVICE_LOCAL_FALLBACK_PRUNE_OLDER_THAN_SECONDS="${SQL_LINK_SERVICE_LOCAL_FALLBACK_PRUNE_OLDER_THAN_SECONDS:-21600}"
export SQL_LINK_SERVICE_LOCAL_FALLBACK_PRUNE_MAX_FILES="${SQL_LINK_SERVICE_LOCAL_FALLBACK_PRUNE_MAX_FILES:-400}"
export SQL_LINK_SERVICE_SHARDS="${SQL_LINK_SERVICE_SHARDS:-health_fast,trading_fast,crypto_trading_fast,runtime,crypto_runtime,crypto_api_ingress,aggressive_trading,trading,crypto_trading,governance,support_watchdog,crypto_governance,schema_violations,data,explanations,crypto_explanations,shadow_attribution,crypto_shadow_attribution}"
export SQL_LINK_SERVICE_SHARD_HEALTH_FAST_MAX_FILES="${SQL_LINK_SERVICE_SHARD_HEALTH_FAST_MAX_FILES:-12}"
export SQL_LINK_SERVICE_SHARD_CRYPTO_GOVERNANCE_MAX_FILES="${SQL_LINK_SERVICE_SHARD_CRYPTO_GOVERNANCE_MAX_FILES:-12}"
export SQL_LINK_SERVICE_SHARD_CRYPTO_TRADING_FAST_MAX_FILES="${SQL_LINK_SERVICE_SHARD_CRYPTO_TRADING_FAST_MAX_FILES:-8}"
export SQL_LINK_SERVICE_SHARD_CRYPTO_TRADING_MAX_FILES="${SQL_LINK_SERVICE_SHARD_CRYPTO_TRADING_MAX_FILES:-10}"
export SQL_LINK_SERVICE_SHARD_TRADING_FAST_MAX_FILES="${SQL_LINK_SERVICE_SHARD_TRADING_FAST_MAX_FILES:-8}"
export SQL_LINK_SERVICE_WAL_CHECKPOINT_THRESHOLD_GB="${SQL_LINK_SERVICE_WAL_CHECKPOINT_THRESHOLD_GB:-${SQLITE_WAL_CHECKPOINT_THRESHOLD_GB:-2}}"
export SQL_LINK_SERVICE_WAL_CHECKPOINT_TRIGGER_GROWTH_GB="${SQL_LINK_SERVICE_WAL_CHECKPOINT_TRIGGER_GROWTH_GB:-1.5}"
export SQL_LINK_SERVICE_WAL_CHECKPOINT_TRIGGER_ROWS="${SQL_LINK_SERVICE_WAL_CHECKPOINT_TRIGGER_ROWS:-750000}"
export SQL_LINK_SERVICE_HOT_MAX_ROWS="${SQL_LINK_SERVICE_HOT_MAX_ROWS:-3000000}"
export SQL_LINK_SERVICE_HOT_TRIGGER_GROWTH_GB="${SQL_LINK_SERVICE_HOT_TRIGGER_GROWTH_GB:-12}"
export SQL_LINK_SERVICE_HOT_TRIGGER_ROWS="${SQL_LINK_SERVICE_HOT_TRIGGER_ROWS:-2500000}"
export SQL_LINK_SERVICE_HOT_MIN_INTERVAL_SECONDS="${SQL_LINK_SERVICE_HOT_MIN_INTERVAL_SECONDS:-180}"
export SQL_LINK_SERVICE_HOT_VACUUM_THRESHOLD_GB="${SQL_LINK_SERVICE_HOT_VACUUM_THRESHOLD_GB:-150}"
export SQL_LINK_SERVICE_HOT_ARCHIVE_PERIOD="${SQL_LINK_SERVICE_HOT_ARCHIVE_PERIOD:-day}"
export SQL_LINK_SERVICE_HOT_ARCHIVE_PRUNE_VACUUM="${SQL_LINK_SERVICE_HOT_ARCHIVE_PRUNE_VACUUM:-1}"
export SQL_LINK_SERVICE_HOT_ARCHIVE_RETENTION_DAYS="${SQL_LINK_SERVICE_HOT_ARCHIVE_RETENTION_DAYS:-7}"
export AUTO_RETRAIN_SWAP_SOFT_MAX_GB="${AUTO_RETRAIN_SWAP_SOFT_MAX_GB:-32}"
export AUTO_RETRAIN_SWAP_IGNORE_IF_FREE_PCT_AT_LEAST="${AUTO_RETRAIN_SWAP_IGNORE_IF_FREE_PCT_AT_LEAST:-70}"
export MEMORY_THROTTLE_SWAP_SOFT_MAX_GB="${MEMORY_THROTTLE_SWAP_SOFT_MAX_GB:-${AUTO_RETRAIN_SWAP_SOFT_MAX_GB:-32}}"
export MEMORY_THROTTLE_SWAP_IGNORE_IF_FREE_PCT_AT_LEAST="${MEMORY_THROTTLE_SWAP_IGNORE_IF_FREE_PCT_AT_LEAST:-${AUTO_RETRAIN_SWAP_IGNORE_IF_FREE_PCT_AT_LEAST:-70}}"
export ASYNC_PIPELINE_WORKERS="${ASYNC_PIPELINE_WORKERS:-4}"
export OPS_SUPPORT_JOB_NICE="${OPS_SUPPORT_JOB_NICE:-5}"
export OPS_SUPPORT_JOBS_BACKGROUND_POLICY="${OPS_SUPPORT_JOBS_BACKGROUND_POLICY:-1}"
export OPS_SUPPORT_HEAVY_COLLECTOR_COOLDOWN_SECONDS="${OPS_SUPPORT_HEAVY_COLLECTOR_COOLDOWN_SECONDS:-300}"
export OPS_SUPPORT_HEAVY_COLLECTOR_MAX_CPU_PERCENT="${OPS_SUPPORT_HEAVY_COLLECTOR_MAX_CPU_PERCENT:-55}"
export SUPPORT_MAINTENANCE_CONCURRENCY="${SUPPORT_MAINTENANCE_CONCURRENCY:-2}"
export LIVE_FEED_HEAVY_TAIL_BYTES="${LIVE_FEED_HEAVY_TAIL_BYTES:-262144}"
export LIVE_FEED_HEAVY_BOOTSTRAP_MAX_LINES="${LIVE_FEED_HEAVY_BOOTSTRAP_MAX_LINES:-80}"
export LIVE_FEED_HEAVY_SNAPSHOT_MAX_LINES="${LIVE_FEED_HEAVY_SNAPSHOT_MAX_LINES:-180}"
export LIVE_FEED_MAX_LINE_CHARS="${LIVE_FEED_MAX_LINE_CHARS:-1400}"
export LIVE_FEED_DECISION_MAX_AGE_HOURS="${LIVE_FEED_DECISION_MAX_AGE_HOURS:-48}"
export FEATURE_WINDOW_CACHE_ENABLED="${FEATURE_WINDOW_CACHE_ENABLED:-1}"
export RUNTIME_FEATURE_CACHE_MAX_ENTRIES="${RUNTIME_FEATURE_CACHE_MAX_ENTRIES:-192}"
export RUNTIME_SLOW_BOT_CACHE_MAX_SYMBOLS="${RUNTIME_SLOW_BOT_CACHE_MAX_SYMBOLS:-48}"
export SCHWAB_NEWS_CACHE_MAX_SYMBOLS="${SCHWAB_NEWS_CACHE_MAX_SYMBOLS:-64}"
export SCHWAB_OPTIONS_CHAIN_CACHE_MAX_SYMBOLS="${SCHWAB_OPTIONS_CHAIN_CACHE_MAX_SYMBOLS:-64}"
export RUNTIME_TRAIN_SAMPLE_STRIDE_FLOOR="${RUNTIME_TRAIN_SAMPLE_STRIDE_FLOOR:-1}"
export RUNTIME_TRAIN_BATCH_SIZE_CAP="${RUNTIME_TRAIN_BATCH_SIZE_CAP:-96}"
export RUNTIME_TRAIN_MAX_SAMPLES="${RUNTIME_TRAIN_MAX_SAMPLES:-0}"
export BOT_LOGS_LOW_SPACE_AUTOPRUNE_ENABLED="${BOT_LOGS_LOW_SPACE_AUTOPRUNE_ENABLED:-1}"
export BOT_LOGS_LOW_SPACE_AUTOPRUNE_MIN_FREE_GB="${BOT_LOGS_LOW_SPACE_AUTOPRUNE_MIN_FREE_GB:-100}"
export RETENTION_DECISIONS_DAYS="${RETENTION_DECISIONS_DAYS:-5}"
export RETENTION_DECISION_EXPLANATIONS_DAYS="${RETENTION_DECISION_EXPLANATIONS_DAYS:-5}"
export LOG_RETENTION_DECISIONS_DAYS="${LOG_RETENTION_DECISIONS_DAYS:-${RETENTION_DECISIONS_DAYS:-5}}"
export LOG_RETENTION_DECISION_EXPLANATIONS_DAYS="${LOG_RETENTION_DECISION_EXPLANATIONS_DAYS:-${RETENTION_DECISION_EXPLANATIONS_DAYS:-5}}"
export LOG_COMPRESS_AFTER_DAYS="${LOG_COMPRESS_AFTER_DAYS:-0.25}"
export RETENTION_DATA_LOCAL_FALLBACK_DAYS="${RETENTION_DATA_LOCAL_FALLBACK_DAYS:-1}"
export RETENTION_EXTERNAL_LIVE_SQLITE_DAYS="${RETENTION_EXTERNAL_LIVE_SQLITE_DAYS:-1}"
export RETENTION_EXTERNAL_LIVE_SQLITE_REQUIRE_LOCAL_FALLBACK="${RETENTION_EXTERNAL_LIVE_SQLITE_REQUIRE_LOCAL_FALLBACK:-1}"
export RETENTION_EXTERNAL_LIVE_SQLITE_LOW_SPACE_FORCE="${RETENTION_EXTERNAL_LIVE_SQLITE_LOW_SPACE_FORCE:-1}"
export RETENTION_EXTERNAL_LIVE_SQLITE_ALLOW_EXTERNAL_MODE_PRESSURE_PRUNE="${RETENTION_EXTERNAL_LIVE_SQLITE_ALLOW_EXTERNAL_MODE_PRESSURE_PRUNE:-1}"
export RETENTION_STALE_STAGE_ENABLED="${RETENTION_STALE_STAGE_ENABLED:-1}"
export RETENTION_STALE_PURGE_ENABLED="${RETENTION_STALE_PURGE_ENABLED:-1}"
export RETENTION_STALE_PURGE_DAYS="${RETENTION_STALE_PURGE_DAYS:-30}"
export RETENTION_STALE_PURGE_LOW_VALUE_DAYS="${RETENTION_STALE_PURGE_LOW_VALUE_DAYS:-7}"
export RETENTION_STALE_PURGE_MEDIUM_VALUE_DAYS="${RETENTION_STALE_PURGE_MEDIUM_VALUE_DAYS:-21}"
export RETENTION_STALE_PURGE_HIGH_VALUE_DAYS="${RETENTION_STALE_PURGE_HIGH_VALUE_DAYS:-45}"
export RETENTION_STALE_PURGE_CRITICAL_VALUE_DAYS="${RETENTION_STALE_PURGE_CRITICAL_VALUE_DAYS:-90}"
export RETENTION_STALE_PURGE_MAX_FILES="${RETENTION_STALE_PURGE_MAX_FILES:-5000}"
export RETENTION_STALE_PURGE_MAX_GB="${RETENTION_STALE_PURGE_MAX_GB:-10}"
export RETENTION_ARCHIVE_PRUNE_ENABLED="${RETENTION_ARCHIVE_PRUNE_ENABLED:-1}"
export RETENTION_ARCHIVE_DB="${RETENTION_ARCHIVE_DB:-$PROJECT_ROOT/data/jsonl_link_archive.sqlite3}"
export RETENTION_ARCHIVE_ROOT="${RETENTION_ARCHIVE_ROOT:-$PROJECT_ROOT/data/jsonl_link_archives}"
export RETENTION_ARCHIVE_RETENTION_DAYS="${RETENTION_ARCHIVE_RETENTION_DAYS:-${SQL_LINK_SERVICE_HOT_ARCHIVE_RETENTION_DAYS:-7}}"
export RETENTION_ARCHIVE_PRUNE_VACUUM="${RETENTION_ARCHIVE_PRUNE_VACUUM:-${SQL_LINK_SERVICE_HOT_ARCHIVE_PRUNE_VACUUM:-1}}"
export RETENTION_ARCHIVE_COLD_EXPORT_ROOT="${RETENTION_ARCHIVE_COLD_EXPORT_ROOT:-${SQL_LINK_SERVICE_HOT_COLD_ARCHIVE_ROOT:-}}"
export RETENTION_ARCHIVE_COLD_EXPORT_FORMAT="${RETENTION_ARCHIVE_COLD_EXPORT_FORMAT:-${SQL_LINK_SERVICE_HOT_COLD_ARCHIVE_FORMAT:-parquet}}"
export RETENTION_ARCHIVE_COLD_EXPORT_BATCH_SIZE="${RETENTION_ARCHIVE_COLD_EXPORT_BATCH_SIZE:-${SQL_LINK_SERVICE_HOT_COLD_ARCHIVE_BATCH_SIZE:-50000}}"
export RETENTION_ARCHIVE_COLD_EXPORT_COMPRESSION="${RETENTION_ARCHIVE_COLD_EXPORT_COMPRESSION:-${SQL_LINK_SERVICE_HOT_COLD_ARCHIVE_COMPRESSION:-zstd}}"
export CONTENT_STORE_GC_ENABLED="${CONTENT_STORE_GC_ENABLED:-1}"
export CONTENT_STORE_GC_GRACE_DAYS="${CONTENT_STORE_GC_GRACE_DAYS:-1}"
export CONTENT_STORE_MAX_BLOB_GB="${CONTENT_STORE_MAX_BLOB_GB:-0.5}"
export RETENTION_REFRESH_INTERVAL_SECONDS="${RETENTION_REFRESH_INTERVAL_SECONDS:-3600}"
export FINDER_LOG_REFRESH_LAUNCHD_ENABLED="${FINDER_LOG_REFRESH_LAUNCHD_ENABLED:-0}"
export FINDER_LOG_REFRESH_INTERVAL_SECONDS="${FINDER_LOG_REFRESH_INTERVAL_SECONDS:-1800}"
export RESOURCE_GUARD_MEMORY_YELLOW_AVAILABLE_PCT="${RESOURCE_GUARD_MEMORY_YELLOW_AVAILABLE_PCT:-50}"
export RESOURCE_GUARD_MEMORY_YELLOW_FREE_PCT="${RESOURCE_GUARD_MEMORY_YELLOW_FREE_PCT:-8}"
export RESOURCE_GUARD_MEMORY_YELLOW_SWAP_GB="${RESOURCE_GUARD_MEMORY_YELLOW_SWAP_GB:-12}"
export RESOURCE_GUARD_MEMORY_YELLOW_SWAP_RELAX_AVAILABLE_PCT="${RESOURCE_GUARD_MEMORY_YELLOW_SWAP_RELAX_AVAILABLE_PCT:-60}"
export RESOURCE_GUARD_MEMORY_RED_AVAILABLE_PCT="${RESOURCE_GUARD_MEMORY_RED_AVAILABLE_PCT:-35}"
export RESOURCE_GUARD_MEMORY_RED_FREE_PCT="${RESOURCE_GUARD_MEMORY_RED_FREE_PCT:-4}"
export RESOURCE_GUARD_MEMORY_RED_SWAP_GB="${RESOURCE_GUARD_MEMORY_RED_SWAP_GB:-18}"
export RESOURCE_GUARD_MEMORY_RED_THROTTLED_PAGES="${RESOURCE_GUARD_MEMORY_RED_THROTTLED_PAGES:-1}"
export RESOURCE_GUARD_CREATIVE_APP_NAMES="${RESOURCE_GUARD_CREATIVE_APP_NAMES:-Final Cut Pro,Logic Pro,Music,iTunes}"
export RESOURCE_GUARD_CREATIVE_HOT_CPU_THRESHOLD="${RESOURCE_GUARD_CREATIVE_HOT_CPU_THRESHOLD:-140}"
export RESOURCE_GUARD_LOGIC_HOT_CPU_THRESHOLD="${RESOURCE_GUARD_LOGIC_HOT_CPU_THRESHOLD:-80}"
export RESOURCE_GUARD_FINAL_CUT_HOT_CPU_THRESHOLD="${RESOURCE_GUARD_FINAL_CUT_HOT_CPU_THRESHOLD:-140}"
export RESOURCE_GUARD_MUSIC_HOT_CPU_THRESHOLD="${RESOURCE_GUARD_MUSIC_HOT_CPU_THRESHOLD:-45}"
export RESOURCE_GUARD_BLOCK_ON_CREATIVE_SESSION_LEVELS="${RESOURCE_GUARD_BLOCK_ON_CREATIVE_SESSION_LEVELS:-dual_pro,hot}"
export RESOURCE_GUARD_OPTIONAL_BLOCK_ON_MEMORY_STATES="${RESOURCE_GUARD_OPTIONAL_BLOCK_ON_MEMORY_STATES:-yellow,red}"
export RESOURCE_GUARD_OPTIONAL_BLOCK_ON_CREATIVE_SESSION_LEVELS="${RESOURCE_GUARD_OPTIONAL_BLOCK_ON_CREATIVE_SESSION_LEVELS:-active,dual_pro,hot}"
export RESOURCE_GUARD_OPTIONAL_MAX_LOAD_PER_CORE="${RESOURCE_GUARD_OPTIONAL_MAX_LOAD_PER_CORE:-2.4}"
export RESOURCE_GUARD_OPTIONAL_MIN_DISK_GB="${RESOURCE_GUARD_OPTIONAL_MIN_DISK_GB:-20}"
export RESOURCE_GUARD_OPTIONAL_MAX_EDITING_CPU="${RESOURCE_GUARD_OPTIONAL_MAX_EDITING_CPU:-300}"
export RESOURCE_GUARD_REFRESH_BLOCK_ON_CREATIVE_SESSION_LEVELS="${RESOURCE_GUARD_REFRESH_BLOCK_ON_CREATIVE_SESSION_LEVELS:-dual_pro,hot}"
export CREATIVE_COTENANT_GUARD_INTERVAL_SECONDS="${CREATIVE_COTENANT_GUARD_INTERVAL_SECONDS:-20}"
export CREATIVE_COTENANT_COOLDOWN_SECONDS="${CREATIVE_COTENANT_COOLDOWN_SECONDS:-600}"
export MEMORY_EFFICIENCY_CREATIVE_ACTIVE_MAX_PROFILE="${MEMORY_EFFICIENCY_CREATIVE_ACTIVE_MAX_PROFILE:-air_safe}"
export MEMORY_EFFICIENCY_CREATIVE_LOGIC_PROFILE="${MEMORY_EFFICIENCY_CREATIVE_LOGIC_PROFILE:-pro_balanced}"
export MEMORY_EFFICIENCY_CREATIVE_FINAL_CUT_PROFILE="${MEMORY_EFFICIENCY_CREATIVE_FINAL_CUT_PROFILE:-air_safe}"
export MEMORY_EFFICIENCY_CREATIVE_MUSIC_PROFILE="${MEMORY_EFFICIENCY_CREATIVE_MUSIC_PROFILE:-air_safe}"
export MEMORY_EFFICIENCY_CREATIVE_HOT_PROFILE="${MEMORY_EFFICIENCY_CREATIVE_HOT_PROFILE:-constrained}"
export MEMORY_EFFICIENCY_CREATIVE_DUAL_PROFILE="${MEMORY_EFFICIENCY_CREATIVE_DUAL_PROFILE:-constrained}"
export MEMORY_EFFICIENCY_CREATIVE_COOLDOWN_PROFILE="${MEMORY_EFFICIENCY_CREATIVE_COOLDOWN_PROFILE:-air_safe}"
export SWAP_PRESSURE_GOVERNOR_INTERVAL_SECONDS="${SWAP_PRESSURE_GOVERNOR_INTERVAL_SECONDS:-60}"
export SWAP_PRESSURE_CALM_GB="${SWAP_PRESSURE_CALM_GB:-10}"
export SWAP_PRESSURE_CONSTRAINED_GB="${SWAP_PRESSURE_CONSTRAINED_GB:-14}"
export SWAP_PRESSURE_PAUSE_RESEARCH_GB="${SWAP_PRESSURE_PAUSE_RESEARCH_GB:-18}"
export SWAP_PRESSURE_SURVIVAL_GB="${SWAP_PRESSURE_SURVIVAL_GB:-22}"
export SWAP_PRESSURE_RESUME_GB="${SWAP_PRESSURE_RESUME_GB:-8}"
export SWAP_PRESSURE_RESTART_CANDIDATE_RSS_MB="${SWAP_PRESSURE_RESTART_CANDIDATE_RSS_MB:-512}"
export SWAP_PRESSURE_REBOOT_RECOMMEND_GB="${SWAP_PRESSURE_REBOOT_RECOMMEND_GB:-18}"
export SWAP_PRESSURE_REBOOT_RECOMMEND_MINUTES="${SWAP_PRESSURE_REBOOT_RECOMMEND_MINUTES:-30}"
export AGGRESSIVE_SPLIT_INGRESS_LOOPS="${AGGRESSIVE_SPLIT_INGRESS_LOOPS:-1}"
export AGGRESSIVE_SPLIT_STAGGER_SECONDS="${AGGRESSIVE_SPLIT_STAGGER_SECONDS:-2}"
export INTRADAY_AGGRESSIVE_DEFENSIVE_INTERVAL_SECONDS="${INTRADAY_AGGRESSIVE_DEFENSIVE_INTERVAL_SECONDS:-24}"
export SWING_AGGRESSIVE_DEFENSIVE_INTERVAL_SECONDS="${SWING_AGGRESSIVE_DEFENSIVE_INTERVAL_SECONDS:-180}"

ACCESS_MODE_RAW="${BOT_RUNTIME_ACCESS_MODE:-native}"
case "${ACCESS_MODE_RAW:l}" in
  portable|export|accessible)
    export BOT_RUNTIME_ACCESS_MODE="portable"
    export BOT_LOGS_PREFER_EXTERNAL="0"
    export BOT_PORTABLE_RUNTIME="1"
    export BOT_SQL_ACCESS_PORTABLE="1"
    export BOT_ML_RUNTIME_OPTIONAL="${BOT_ML_RUNTIME_OPTIONAL:-1}"
    export BOT_ML_BACKEND="${BOT_ML_BACKEND:-portable_auto}"
    export BOT_MLX_OPTIONAL="${BOT_MLX_OPTIONAL:-$BOT_ML_RUNTIME_OPTIONAL}"
    export RUNTIME_TRAIN_USE_SNAPSHOT="${RUNTIME_TRAIN_USE_SNAPSHOT:-1}"
    export RUNTIME_TRAIN_PREFER_SQLITE="${RUNTIME_TRAIN_PREFER_SQLITE:-1}"
    export RUNTIME_TRAIN_SNAPSHOT_PREFER_SQLITE="${RUNTIME_TRAIN_SNAPSHOT_PREFER_SQLITE:-1}"
    export RUNTIME_TRAIN_SQLITE_PATH="${RUNTIME_TRAIN_SQLITE_PATH:-$PROJECT_ROOT/data/jsonl_link.sqlite3}"
    export MLX_METAL_JIT="${MLX_METAL_JIT:-0}"
    ;;
  *)
    export BOT_RUNTIME_ACCESS_MODE="native"
    export BOT_PORTABLE_RUNTIME="${BOT_PORTABLE_RUNTIME:-0}"
    export BOT_SQL_ACCESS_PORTABLE="${BOT_SQL_ACCESS_PORTABLE:-0}"
    export BOT_ML_RUNTIME_OPTIONAL="${BOT_ML_RUNTIME_OPTIONAL:-0}"
    export BOT_ML_BACKEND="${BOT_ML_BACKEND:-native_default}"
    export BOT_MLX_OPTIONAL="${BOT_MLX_OPTIONAL:-$BOT_ML_RUNTIME_OPTIONAL}"
    ;;
esac

case "${BOT_ML_BACKEND:l}" in
  ""|auto)
    if [[ "$BOT_RUNTIME_ACCESS_MODE" == "portable" ]]; then
      export BOT_ML_BACKEND="portable_auto"
    else
      export BOT_ML_BACKEND="native_default"
    fi
    ;;
esac

if [[ "$QUIET" != "--quiet" ]]; then
  loaded="none"
  if (( ${#LOADED_FILES[@]} > 0 )); then
    loaded="${(j:,:)LOADED_FILES}"
  fi
  echo "runtime_env_loaded profile=$PROFILE access_mode=$BOT_RUNTIME_ACCESS_MODE files=$loaded"
fi
