#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import pprint
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[2]
REGISTRY_PATH = PROJECT_ROOT / "master_bot_registry.json"
CORE_DIR = PROJECT_ROOT / "core"
GENERATED_MARKER = "Generated by scripts/ops/materialize_core_bot_modules.py"


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _load_json(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}
    return payload if isinstance(payload, dict) else {}


def _safe_symbol(raw: str) -> str:
    value = re.sub(r"[^A-Za-z0-9_]", "_", raw.strip().upper())
    return re.sub(r"_+", "_", value).strip("_") or "REGISTRY_BACKED_BOT"


def _row_is_materializable(row: dict[str, Any]) -> bool:
    bot_id = str(row.get("bot_id") or "").strip()
    if not bot_id.startswith("brain_refinery_v"):
        return False
    has_registry_identity = bool(str(row.get("slot_label") or "").strip()) and bool(str(row.get("slot_kind") or "").strip())
    return (
        bool(row.get("active"))
        and bool(row.get("data_collection_active"))
        and str(row.get("lifecycle_state") or "") == "data_collection_only"
        and has_registry_identity
        and not bool(row.get("trading_enabled"))
        and not bool(row.get("live_trading_enabled"))
        and not bool(row.get("execution_enabled"))
        and not bool(row.get("allocation_enabled"))
    )


def _compact_spec(row: dict[str, Any]) -> dict[str, Any]:
    keys = [
        "bot_id",
        "bot_role",
        "active",
        "lifecycle_state",
        "slot_label",
        "slot_kind",
        "sleeve_profile",
        "sleeve_family",
        "slot_priority",
        "slot_objective",
        "target_functions",
        "preferred_regimes",
        "bootstrap_teacher_bot_ids",
        "correlation_peer_sleeves",
        "correlation_dependencies",
        "label_contract",
        "data_label_contract_version",
        "labeling_tags",
        "execution_policy_label",
        "data_intake_collections",
        "storage_targets",
        "freshness_slo_seconds",
        "retention_profile",
        "provider_capability_profile",
        "direct_market_data_available",
        "direct_execution_allowed",
        "proxy_data_sources",
        "schwab_direct_inputs",
        "proxy_only_reason",
        "data_collection_active",
        "data_collection_mode",
        "data_collection_reason",
        "data_collection_observations",
        "training_excluded",
        "exclude_from_training",
        "training_candidate_after_threshold",
        "training_threshold_policy",
        "minimum_training_observations",
        "minimum_data_collection_days",
        "trading_enabled",
        "paper_trading_enabled",
        "live_trading_enabled",
        "allocation_enabled",
        "execution_enabled",
        "rotation_blocked",
        "rotation_block_reason",
        "capability_pack_version",
        "capability_pack_slug",
        "capability_pack_display_name",
        "capability_pack_contract",
        "advanced_intelligence_layer_contract",
        "apex_self_awareness_intelligence_contract",
        "deep_recursive_awareness_contract",
        "frontier_intelligence_contract",
        "institutional_alpha_validation_contract",
        "quant_strategy_gap_contract",
        "platform_organ_systems_contract",
        "trading_muscle_systems_contract",
        "platform_brain_v6_contract",
    ]
    return {key: row.get(key) for key in keys if key in row}


def _module_source(row: dict[str, Any]) -> str:
    spec = _compact_spec(row)
    bot_id = str(spec.get("bot_id") or "")
    symbol = _safe_symbol(bot_id)
    label = str(spec.get("slot_label") or bot_id)
    generated_at = _utc_now()
    spec_text = pprint.pformat(spec, sort_dicts=True, width=100)
    return f'''"""Registry-backed collection module for {label}.

{GENERATED_MARKER}

This file exists so the bot is visible and inspectable in PyCharm. The master
registry still controls whether the bot can train, allocate, paper trade, or
live trade.
"""

from __future__ import annotations

try:
    from registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot
except ModuleNotFoundError:
    from core.registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot

BOT_ID = {bot_id!r}
GENERATED_AT_UTC = {generated_at!r}
BOT_SPEC = {spec_text}
{symbol}_SPEC = BOT_SPEC


def describe_bot():
    return describe_registry_backed_bot(BOT_SPEC)


def train_brain():
    return train_registry_backed_bot(BOT_SPEC)


if __name__ == "__main__":
    print(describe_bot())
'''


def materialize(project_root: Path, overwrite_generated: bool = False) -> dict[str, Any]:
    registry = _load_json(project_root / "master_bot_registry.json")
    rows = [row for row in registry.get("sub_bots", []) if isinstance(row, dict)]
    core_dir = project_root / "core"
    core_dir.mkdir(parents=True, exist_ok=True)

    created: list[str] = []
    updated: list[str] = []
    skipped_existing: list[str] = []
    materializable = [row for row in rows if _row_is_materializable(row)]

    for row in materializable:
        bot_id = str(row.get("bot_id") or "").strip()
        path = core_dir / f"{bot_id}.py"
        source = _module_source(row)
        if path.exists():
            existing = path.read_text(encoding="utf-8", errors="replace")
            if overwrite_generated and GENERATED_MARKER in existing:
                path.write_text(source, encoding="utf-8")
                updated.append(str(path.relative_to(project_root)))
            else:
                skipped_existing.append(str(path.relative_to(project_root)))
            continue
        path.write_text(source, encoding="utf-8")
        created.append(str(path.relative_to(project_root)))

    return {
        "ok": True,
        "generated_at_utc": _utc_now(),
        "materializable_count": len(materializable),
        "created_count": len(created),
        "updated_count": len(updated),
        "skipped_existing_count": len(skipped_existing),
        "created": created,
        "updated": updated,
        "skipped_existing": skipped_existing,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Create PyCharm-visible core/*.py files for registry-backed collection bots.")
    parser.add_argument("--project-root", default=str(PROJECT_ROOT))
    parser.add_argument("--overwrite-generated", action="store_true")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    payload = materialize(Path(args.project_root).resolve(), overwrite_generated=bool(args.overwrite_generated))
    if args.json:
        print(json.dumps(payload, ensure_ascii=True, indent=2))
    else:
        print(
            "materialize_core_bot_modules "
            f"created={payload['created_count']} updated={payload['updated_count']} "
            f"skipped_existing={payload['skipped_existing_count']} materializable={payload['materializable_count']}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
