#!/bin/zsh
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
export BOT_RUNTIME_LANE="${BOT_RUNTIME_LANE:-${BOT_SHADOW_RUNTIME_LANE:-canary314}}"
export BOT_PYTHON_VERSION="${BOT_PYTHON_VERSION:-3.14.5}"
export BOT_TRAINING_RUNTIME_LANE="${BOT_TRAINING_RUNTIME_LANE:-canary314}"
export BOT_TRAINING_PYTHON_VERSION="${BOT_TRAINING_PYTHON_VERSION:-3.14.5}"
export PY314_RUNTIME_FLIP_APPROVED="${PY314_RUNTIME_FLIP_APPROVED:-1}"
export PY314_RETIRE_312_ANCHOR="${PY314_RETIRE_312_ANCHOR:-1}"
unset __PYVENV_LAUNCHER__
source "$PROJECT_ROOT/scripts/ops/runtime_python.sh"
PROFILE="${BOT_RUNTIME_PROFILE:-live}"

cd "$PROJECT_ROOT"

if [[ -f "$PROJECT_ROOT/scripts/ops/load_runtime_env.sh" ]]; then
  # shellcheck disable=SC1091
  source "$PROJECT_ROOT/scripts/ops/load_runtime_env.sh" "$PROFILE" --quiet
fi

export BOT_RUNTIME_PROFILE="${BOT_RUNTIME_PROFILE:-$PROFILE}"
PYTHON_BIN="$(resolve_runtime_python)"
export MARKET_DATA_ONLY="${MARKET_DATA_ONLY:-1}"
export ALLOW_ORDER_EXECUTION="${ALLOW_ORDER_EXECUTION:-0}"
export PAPER_TRADE_LOCK_PATH="${PAPER_TRADE_LOCK_PATH:-$PROJECT_ROOT/governance/health/PAPER_TRADE_LOCK.flag}"
mkdir -p "$(dirname "$PAPER_TRADE_LOCK_PATH")"
printf 'enabled_at_utc=%s\npolicy=live_data_paper_trade_only\nmanaged_by=run_all_sleeves_launchd\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$PAPER_TRADE_LOCK_PATH"
export PAPER_TRADE_LOCK="${PAPER_TRADE_LOCK:-1}"
export TOP_BOT_ENABLE_LIVE_EXECUTION="${TOP_BOT_ENABLE_LIVE_EXECUTION:-0}"
export EXECUTION_LANE_LIVE_ENABLED="${EXECUTION_LANE_LIVE_ENABLED:-0}"
export RUN_ALL_SLEEVES_WITH_LIVE_EXECUTOR="${RUN_ALL_SLEEVES_WITH_LIVE_EXECUTOR:-0}"
export INLINE_PAPER_EXECUTION_ENABLED="${INLINE_PAPER_EXECUTION_ENABLED:-0}"
export MARKET_SESSION_START_HOUR="${MARKET_SESSION_START_HOUR:-4}"
export LOG_SUB_BOT_DECISIONS="${LOG_SUB_BOT_DECISIONS:-1}"
export LOG_MASTER_VARIANT_DECISIONS="${LOG_MASTER_VARIANT_DECISIONS:-1}"
export LOG_GRAND_MASTER_DECISIONS="${LOG_GRAND_MASTER_DECISIONS:-1}"
export LOG_OPTIONS_MASTER_DECISIONS="${LOG_OPTIONS_MASTER_DECISIONS:-1}"
export LOG_FUTURES_MASTER_DECISIONS="${LOG_FUTURES_MASTER_DECISIONS:-1}"

# Enable paper mirror for Schwab sleeves while keeping live execution disabled.
export TOP_BOT_PAPER_TRADING_ENABLED="1"
export TOP_BOT_PAPER_TRADING_TOP_N="${TOP_BOT_PAPER_TRADING_TOP_N:-5}"
export TOP_BOT_PAPER_TRADING_MIN_ACC="${TOP_BOT_PAPER_TRADING_MIN_ACC:-0.55}"
export TOP_BOT_PAPER_TRADING_PROFILES="default,conservative,aggressive,intraday_aggressive,swing_aggressive,dividend,bond,fx"
export RUN_ALL_SLEEVES_WITH_FX="${RUN_ALL_SLEEVES_WITH_FX:-1}"
export RUN_ALL_SLEEVES_WITH_DIVIDEND_CAPTURE="${RUN_ALL_SLEEVES_WITH_DIVIDEND_CAPTURE:-1}"
export TOP_BOT_PAPER_TRADING_OPTIONS_ENABLED="${TOP_BOT_PAPER_TRADING_OPTIONS_ENABLED:-1}"
export TOP_BOT_PAPER_TRADING_OPTIONS_TOP_N="${TOP_BOT_PAPER_TRADING_OPTIONS_TOP_N:-2}"
export TOP_BOT_PAPER_TRADING_OPTIONS_MIN_ACC="${TOP_BOT_PAPER_TRADING_OPTIONS_MIN_ACC:-0.55}"
export TOP_BOT_PAPER_TRADING_OPTIONS_PROFILES="${TOP_BOT_PAPER_TRADING_OPTIONS_PROFILES:-default,aggressive,intraday_aggressive,swing_aggressive,options_on_futures,options_on_futures_aggressive}"
export PAPER_BROKER_BRIDGE_ENABLED="${PAPER_BROKER_BRIDGE_ENABLED:-1}"
export PAPER_BROKER_BRIDGE_MODE="${PAPER_BROKER_BRIDGE_MODE:-jsonl}"
export ALL_SLEEVES_HEALTH_WRITE_SECONDS="${ALL_SLEEVES_HEALTH_WRITE_SECONDS:-15}"
export OPS_WATCHDOG_ALL_SLEEVES_MIN_CHILDREN="${OPS_WATCHDOG_ALL_SLEEVES_MIN_CHILDREN:-4}"
export OPS_WATCHDOG_ALL_SLEEVES_CHILD_GRACE_SECONDS="${OPS_WATCHDOG_ALL_SLEEVES_CHILD_GRACE_SECONDS:-180}"

exec "$PYTHON_BIN" "$PROJECT_ROOT/scripts/run_all_sleeves.py" \
  --with-aggressive-modes \
  --disable-circuit-breakers
