#!/bin/zsh
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd -P)"
PYTHON_BIN="$PROJECT_ROOT/.venv314/bin/python"
PROFILE="${BOT_RUNTIME_PROFILE:-live}"

cd "$PROJECT_ROOT"

if [[ -f "$PROJECT_ROOT/scripts/ops/load_runtime_env.sh" ]]; then
  # shellcheck disable=SC1091
  source "$PROJECT_ROOT/scripts/ops/load_runtime_env.sh" "$PROFILE" --quiet
fi

export BOT_RUNTIME_PROFILE="${BOT_RUNTIME_PROFILE:-$PROFILE}"
export MAC_NOTIFICATION_WATCH_POLL_SECONDS="${MAC_NOTIFICATION_WATCH_POLL_SECONDS:-30}"
export MAC_NOTIFICATION_WATCH_POWER_EVENTS_ENABLED="${MAC_NOTIFICATION_WATCH_POWER_EVENTS_ENABLED:-1}"
export MAC_NOTIFICATION_WATCH_PMSET_CACHE_SECONDS="${MAC_NOTIFICATION_WATCH_PMSET_CACHE_SECONDS:-900}"
export MAC_NOTIFICATION_WATCH_SKIP_PMSET_UNDER_PRESSURE="${MAC_NOTIFICATION_WATCH_SKIP_PMSET_UNDER_PRESSURE:-1}"

exec "$PYTHON_BIN" "$PROJECT_ROOT/scripts/ops/mac_notification_watch.py"   --poll-seconds "$MAC_NOTIFICATION_WATCH_POLL_SECONDS"
