"""Registry-backed collection module for Intraday News-Spike Absorption Bot.

Generated by scripts/ops/materialize_core_bot_modules.py

This file exists so the bot is visible and inspectable in PyCharm. The master
registry still controls whether the bot can train, allocate, paper trade, or
live trade.
"""

from __future__ import annotations

try:
    from registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot
except ModuleNotFoundError:
    from core.registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot

BOT_ID = 'brain_refinery_v169_intraday_news_spike_absorption_bot'
GENERATED_AT_UTC = '2026-05-01T17:00:28.871023+00:00'
BOT_SPEC = {'active': True,
 'allocation_enabled': False,
 'bootstrap_teacher_bot_ids': ['brain_refinery_v12_news_shocks',
                               'brain_refinery_v156_macro_news_latency_decay_filter'],
 'bot_id': 'brain_refinery_v169_intraday_news_spike_absorption_bot',
 'bot_role': 'signal_sub_bot',
 'correlation_dependencies': [],
 'correlation_peer_sleeves': [],
 'data_collection_active': True,
 'data_collection_mode': 'active_observer',
 'data_collection_observations': 109,
 'data_collection_reason': 'active_observer_until_minimum_samples',
 'data_intake_collections': ['registry_slot_metadata',
                             'training_diagnostics',
                             'walk_forward_requalification',
                             'one_minute_bars',
                             'tick_proxy_microstructure',
                             'relative_volume',
                             'bid_ask_spread_quality',
                             'opening_range_state',
                             'vwap_deviation',
                             'macro_event_bulletins',
                             'calendar_event_window',
                             'news_source_consensus'],
 'data_label_contract_version': '',
 'exclude_from_training': True,
 'execution_enabled': False,
 'execution_policy_label': 'collection_only_no_execution',
 'freshness_slo_seconds': 1800,
 'label_contract': {},
 'labeling_tags': ['research_only',
                   'collection_only',
                   'execution_blocked',
                   'sleeve_family:unassigned',
                   'sleeve_profile:unassigned',
                   'data_floor:5000'],
 'lifecycle_state': 'data_collection_only',
 'live_trading_enabled': False,
 'minimum_data_collection_days': 5,
 'minimum_training_observations': 5000,
 'paper_trading_enabled': False,
 'preferred_regimes': ['event_volatility', 'thin_liquidity', 'fragile_transition'],
 'provider_capability_profile': '',
 'proxy_data_sources': [],
 'proxy_only_reason': '',
 'retention_profile': 'hot_intraday_7d_warm_90d',
 'rotation_block_reason': 'data_collection_only_zero_weight',
 'rotation_blocked': True,
 'schwab_direct_inputs': [],
 'sleeve_family': '',
 'sleeve_profile': '',
 'slot_kind': 'aggressive_intraday_signal',
 'slot_label': 'Intraday News-Spike Absorption Bot',
 'slot_objective': 'Trade fast headline spikes only after tape absorption, source consensus, and '
                   'quote freshness prove the move is actionable.',
 'slot_priority': 'high',
 'storage_targets': ['governance/training_diagnostics',
                     'governance/walk_forward',
                     'data/jsonl_link.sqlite3',
                     'data/bot_channel_queue.sqlite3',
                     'exports/market_micro',
                     'exports/external_context/market_micro',
                     'governance/intraday',
                     'governance/events',
                     'exports/external_context/macro'],
 'target_functions': ['macro_bulletin',
                      'market_micro_sync',
                      'runtime_snapshot_cache_control',
                      'feed_refresh'],
 'trading_enabled': False,
 'training_candidate_after_threshold': True,
 'training_excluded': True,
 'training_threshold_policy': 'eligible_when_minimum_observations_and_days_met'}
BRAIN_REFINERY_V169_INTRADAY_NEWS_SPIKE_ABSORPTION_BOT_SPEC = BOT_SPEC


def describe_bot():
    return describe_registry_backed_bot(BOT_SPEC)


def train_brain():
    return train_registry_backed_bot(BOT_SPEC)


if __name__ == "__main__":
    print(describe_bot())
