"""Registry-backed collection module for Exotic Gap Option Jump Risk Bot.

Generated by scripts/ops/materialize_core_bot_modules.py

This file exists so the bot is visible and inspectable in PyCharm. The master
registry still controls whether the bot can train, allocate, paper trade, or
live trade.
"""

from __future__ import annotations

try:
    from registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot
except ModuleNotFoundError:
    from core.registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot

BOT_ID = 'brain_refinery_v1477_exotic_gap_option_jump_risk_bot'
GENERATED_AT_UTC = '2026-05-05T15:22:40.653420+00:00'
BOT_SPEC = {'active': True,
 'allocation_enabled': False,
 'bootstrap_teacher_bot_ids': ['brain_refinery_v154_after_hours_gap_risk_mega_cap_chain',
                               'brain_refinery_v395_black_swan_hedging_vol_spike_liquidity_bot'],
 'bot_id': 'brain_refinery_v1477_exotic_gap_option_jump_risk_bot',
 'bot_role': 'options_sub_bot',
 'correlation_dependencies': ['cross_sleeve_exposure_netting',
                              'correlation_cluster_risk',
                              'rates_credit_macro',
                              'futures_curve_context',
                              'options_vol_surface'],
 'correlation_peer_sleeves': ['barrier_lookback_options',
                              'black_swan_hedging',
                              'single_name_options_event',
                              'options_on_futures',
                              'rates_credit_macro',
                              'futures_rates_curve',
                              'futures_commodity_macro',
                              'pairs_correlation',
                              'volatility',
                              'market_making_liquidity'],
 'data_collection_active': True,
 'data_collection_mode': 'active_observer',
 'data_collection_observations': 0,
 'data_collection_reason': 'active_observer_until_minimum_samples',
 'data_intake_collections': ['registry_slot_metadata',
                             'training_diagnostics',
                             'walk_forward_requalification',
                             'cross_sleeve_correlation_matrix',
                             'correlation_risk_surface',
                             'cross_asset_regime_context',
                             'rates_curve_context',
                             'credit_spread_context',
                             'funding_liquidity_context',
                             'volatility_regime_term_structure',
                             'scenario_stress_ladder',
                             'model_price_sensitivity_grid',
                             'counterparty_liquidity_proxy',
                             'overnight_gap_option_jump',
                             'jump_diffusion_tail_gap',
                             'event_gap_discontinuity',
                             'options_chain_surface',
                             'options_flow_sweeps_blocks',
                             'zero_dte_gamma_profile',
                             'iv_skew_term_structure',
                             'put_call_wall_distance',
                             'spread_execution_quality',
                             'barrier_touch_risk_surface',
                             'lookback_path_extreme_surface',
                             'path_dependent_payoff_ladder',
                             'macro_event_bulletins',
                             'calendar_event_window',
                             'news_source_consensus',
                             'cross_asset_correlation_context'],
 'data_label_contract_version': 'advanced_derivatives_proxy_labels_v1',
 'direct_execution_allowed': False,
 'direct_market_data_available': False,
 'exclude_from_training': True,
 'execution_enabled': False,
 'execution_policy_label': 'research_only_no_execution',
 'freshness_slo_seconds': 1800,
 'label_contract': {},
 'labeling_tags': ['research_only',
                   'collection_only',
                   'proxy_derived',
                   'execution_blocked',
                   'sleeve_family:exotic_derivatives',
                   'sleeve_profile:barrier_lookback_options',
                   'data_floor:2500'],
 'lifecycle_state': 'data_collection_only',
 'live_trading_enabled': False,
 'minimum_data_collection_days': 14,
 'minimum_training_observations': 2500,
 'paper_trading_enabled': False,
 'preferred_regimes': ['open_drive_stress', 'event_volatility', 'risk_off_shock'],
 'provider_capability_profile': 'path_dependent_barrier_lookback_proxy',
 'proxy_data_sources': ['occ_options_volume_open_interest',
                        'cboe_volatility_indices',
                        'occ_option_chain_aggregates',
                        'listed_volatility_etps',
                        'fred_macro_series',
                        'treasury_yield_curve',
                        'sofr_rates'],
 'proxy_only_reason': 'Use listed options, price-path, barrier-distance, and realized-vol proxies; '
                      'no direct barrier or lookback routing.',
 'retention_profile': 'hot_exotic_derivatives_14d_warm_365d',
 'rotation_block_reason': 'data_collection_only_zero_weight',
 'rotation_blocked': True,
 'schwab_direct_inputs': ['listed_option_chains',
                          'listed_equity_etf_quotes',
                          'listed_futures_quotes_when_entitled'],
 'sleeve_family': 'exotic_derivatives',
 'sleeve_profile': 'barrier_lookback_options',
 'slot_kind': 'barrier_lookback_options_gap_option_jump_risk',
 'slot_label': 'Exotic Gap Option Jump Risk Bot',
 'slot_objective': 'Collect overnight jump, discontinuity, barrier breach, and gap-risk labels '
                   'across index, futures, and mega-cap event windows.',
 'slot_priority': 'high',
 'storage_targets': ['governance/exotic_derivatives',
                     'governance/correlation',
                     'governance/rates',
                     'governance/credit',
                     'exports/exotic_derivatives',
                     'exports/external_context/exotic_derivatives',
                     'governance/barrier_lookback_options',
                     'exports/barrier_lookback_options',
                     'governance/training_diagnostics',
                     'governance/walk_forward',
                     'data/jsonl_link.sqlite3',
                     'data/bot_channel_queue.sqlite3',
                     'exports/options_flow',
                     'exports/external_context/options_flow',
                     'governance/options_flow',
                     'governance/events',
                     'exports/external_context/macro'],
 'target_functions': ['collect_options_flow_context',
                      'market_correlation_sync',
                      'macro_bulletin',
                      'paper_execution_calibration',
                      'risk_service',
                      'exotic_derivative_context_sync'],
 'trading_enabled': False,
 'training_candidate_after_threshold': True,
 'training_excluded': True,
 'training_threshold_policy': 'eligible_when_minimum_observations_and_days_met'}
BRAIN_REFINERY_V1477_EXOTIC_GAP_OPTION_JUMP_RISK_BOT_SPEC = BOT_SPEC


def describe_bot():
    return describe_registry_backed_bot(BOT_SPEC)


def train_brain():
    return train_registry_backed_bot(BOT_SPEC)


if __name__ == "__main__":
    print(describe_bot())
