"""Registry-backed collection module for Intraday Lunch-Reversal Liquidity Refill.

Generated by scripts/ops/materialize_core_bot_modules.py

This file exists so the bot is visible and inspectable in PyCharm. The master
registry still controls whether the bot can train, allocate, paper trade, or
live trade.
"""

from __future__ import annotations

try:
    from registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot
except ModuleNotFoundError:
    from core.registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot

BOT_ID = 'brain_refinery_v205_intraday_lunch_reversal_liquidity_refill'
GENERATED_AT_UTC = '2026-05-02T22:30:58.245341+00:00'
BOT_SPEC = {'active': True,
 'allocation_enabled': False,
 'bootstrap_teacher_bot_ids': ['brain_refinery_v44_intraday_scalp_1m_5m',
                               'brain_refinery_v170_intraday_vwap_snapback_scalper'],
 'bot_id': 'brain_refinery_v205_intraday_lunch_reversal_liquidity_refill',
 'bot_role': 'signal_sub_bot',
 'correlation_dependencies': [],
 'correlation_peer_sleeves': [],
 'data_collection_active': True,
 'data_collection_mode': 'active_observer',
 'data_collection_observations': 0,
 'data_collection_reason': 'active_observer_until_minimum_samples',
 'data_intake_collections': ['registry_slot_metadata',
                             'training_diagnostics',
                             'walk_forward_requalification',
                             'one_minute_bars',
                             'tick_proxy_microstructure',
                             'relative_volume',
                             'bid_ask_spread_quality',
                             'opening_range_state',
                             'vwap_deviation',
                             'intraday_tape_speed_context',
                             'intraday_execution_quality',
                             'intraday_liquidity_cliff_state',
                             'opening_auction_state',
                             'closing_auction_state',
                             'vwap_band_context',
                             'first_five_minute_range_state',
                             'ssr_short_sale_restriction_context',
                             'gamma_wall_intraday_context'],
 'data_label_contract_version': '',
 'exclude_from_training': True,
 'execution_enabled': False,
 'execution_policy_label': 'collection_only_no_execution',
 'freshness_slo_seconds': 1800,
 'label_contract': {},
 'labeling_tags': ['research_only',
                   'collection_only',
                   'execution_blocked',
                   'sleeve_family:intraday',
                   'sleeve_profile:intraday_aggressive',
                   'data_floor:5000'],
 'lifecycle_state': 'data_collection_only',
 'live_trading_enabled': False,
 'minimum_data_collection_days': 5,
 'minimum_training_observations': 5000,
 'paper_trading_enabled': False,
 'preferred_regimes': ['mixed_transition', 'thin_liquidity', 'all_weather'],
 'provider_capability_profile': '',
 'proxy_data_sources': [],
 'proxy_only_reason': '',
 'retention_profile': 'hot_intraday_7d_warm_90d',
 'rotation_block_reason': 'data_collection_only_zero_weight',
 'rotation_blocked': True,
 'schwab_direct_inputs': [],
 'sleeve_family': 'intraday',
 'sleeve_profile': 'intraday_aggressive',
 'slot_kind': 'aggressive_intraday_signal',
 'slot_label': 'Intraday Lunch-Reversal Liquidity Refill',
 'slot_objective': 'Observe midday liquidity refill and lunch-hour reversal patterns using spread '
                   'normalization, VWAP repair, and sector breadth stabilization.',
 'slot_priority': 'medium',
 'storage_targets': ['governance/training_diagnostics',
                     'governance/walk_forward',
                     'data/jsonl_link.sqlite3',
                     'data/bot_channel_queue.sqlite3',
                     'exports/market_micro',
                     'exports/external_context/market_micro',
                     'governance/intraday',
                     'exports/external_context/intraday'],
 'target_functions': ['market_micro_sync', 'feed_refresh', 'portfolio_allocator'],
 'trading_enabled': False,
 'training_candidate_after_threshold': True,
 'training_excluded': True,
 'training_threshold_policy': 'eligible_when_minimum_observations_and_days_met'}
BRAIN_REFINERY_V205_INTRADAY_LUNCH_REVERSAL_LIQUIDITY_REFILL_SPEC = BOT_SPEC


def describe_bot():
    return describe_registry_backed_bot(BOT_SPEC)


def train_brain():
    return train_registry_backed_bot(BOT_SPEC)


if __name__ == "__main__":
    print(describe_bot())
