"""Registry-backed collection module for Defensive Options Teacher.

Generated by scripts/ops/materialize_core_bot_modules.py

This file exists so the bot is visible and inspectable in PyCharm. The master
registry still controls whether the bot can train, allocate, paper trade, or
live trade.
"""

from __future__ import annotations

try:
    from registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot
except ModuleNotFoundError:
    from core.registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot

BOT_ID = 'brain_refinery_v109_defensive_options_risk_off_teacher'
GENERATED_AT_UTC = '2026-05-01T17:00:28.837112+00:00'
BOT_SPEC = {'active': True,
 'allocation_enabled': False,
 'bootstrap_teacher_bot_ids': ['brain_refinery_v99_defensive_dividend_concentration'],
 'bot_id': 'brain_refinery_v109_defensive_options_risk_off_teacher',
 'bot_role': 'options_sub_bot',
 'correlation_dependencies': [],
 'correlation_peer_sleeves': [],
 'data_collection_active': True,
 'data_collection_mode': 'active_observer',
 'data_collection_observations': 62,
 'data_collection_reason': 'active_observer_until_minimum_samples',
 'data_intake_collections': ['registry_slot_metadata',
                             'training_diagnostics',
                             'walk_forward_requalification',
                             'options_chain_surface',
                             'options_flow_sweeps_blocks',
                             'zero_dte_gamma_profile',
                             'iv_skew_term_structure',
                             'put_call_wall_distance',
                             'spread_execution_quality'],
 'data_label_contract_version': '',
 'exclude_from_training': True,
 'execution_enabled': False,
 'execution_policy_label': 'collection_only_no_execution',
 'freshness_slo_seconds': 1800,
 'label_contract': {},
 'labeling_tags': ['research_only',
                   'collection_only',
                   'execution_blocked',
                   'sleeve_family:unassigned',
                   'sleeve_profile:unassigned',
                   'data_floor:1500'],
 'lifecycle_state': 'data_collection_only',
 'live_trading_enabled': False,
 'minimum_data_collection_days': 7,
 'minimum_training_observations': 1500,
 'paper_trading_enabled': False,
 'preferred_regimes': ['risk_off_shock', 'bearish', 'event_volatility'],
 'provider_capability_profile': '',
 'proxy_data_sources': [],
 'proxy_only_reason': '',
 'retention_profile': 'hot_options_14d_warm_180d',
 'rotation_block_reason': 'data_collection_only_zero_weight',
 'rotation_blocked': True,
 'schwab_direct_inputs': [],
 'sleeve_family': '',
 'sleeve_profile': '',
 'slot_kind': 'teacher_champion',
 'slot_label': 'Defensive Options Teacher',
 'slot_objective': 'Build a high-quality defensive options teacher for hedging, convexity, and '
                   'risk-off overlays.',
 'slot_priority': 'critical',
 'storage_targets': ['governance/training_diagnostics',
                     'governance/walk_forward',
                     'data/jsonl_link.sqlite3',
                     'data/bot_channel_queue.sqlite3',
                     'exports/options_flow',
                     'exports/external_context/options_flow',
                     'governance/options_flow'],
 'target_functions': ['teacher_quality_guard', 'distill_new_bots', 'paper_execution_calibration'],
 'trading_enabled': False,
 'training_candidate_after_threshold': True,
 'training_excluded': True,
 'training_threshold_policy': 'eligible_when_minimum_observations_and_days_met'}
BRAIN_REFINERY_V109_DEFENSIVE_OPTIONS_RISK_OFF_TEACHER_SPEC = BOT_SPEC


def describe_bot():
    return describe_registry_backed_bot(BOT_SPEC)


def train_brain():
    return train_registry_backed_bot(BOT_SPEC)


if __name__ == "__main__":
    print(describe_bot())
