"""Registry-backed collection module for Order Flow/Microstructure Sweep Block Imbalance Bot.

Generated by scripts/ops/materialize_core_bot_modules.py

This file exists so the bot is visible and inspectable in PyCharm. The master
registry still controls whether the bot can train, allocate, paper trade, or
live trade.
"""

from __future__ import annotations

try:
    from registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot
except ModuleNotFoundError:
    from core.registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot

BOT_ID = 'brain_refinery_v418_order_flow_market_microstructure_sweep_block_imbalance_bot'
GENERATED_AT_UTC = '2026-05-02T22:30:58.350344+00:00'
BOT_SPEC = {'active': True,
 'allocation_enabled': False,
 'bootstrap_teacher_bot_ids': ['brain_refinery_v183_options_sweep_to_block_confirmation',
                               'brain_refinery_v196_market_making_quote_fade_detection'],
 'bot_id': 'brain_refinery_v418_order_flow_market_microstructure_sweep_block_imbalance_bot',
 'bot_role': 'options_sub_bot',
 'correlation_dependencies': ['cross_sleeve_exposure_netting',
                              'correlation_cluster_risk',
                              'rates_credit_macro',
                              'futures_curve_context',
                              'options_vol_surface'],
 'correlation_peer_sleeves': ['high_frequency_market_making',
                              'market_making_liquidity',
                              'gamma_scalping',
                              'options_on_futures',
                              'single_name_options_event',
                              'rates_credit_macro',
                              'futures_rates_curve',
                              'futures_commodity_macro',
                              'pairs_correlation',
                              'volatility'],
 'data_collection_active': True,
 'data_collection_mode': 'active_observer',
 'data_collection_observations': 0,
 'data_collection_reason': 'active_observer_until_minimum_samples',
 'data_intake_collections': ['registry_slot_metadata',
                             'training_diagnostics',
                             'walk_forward_requalification',
                             'cross_sleeve_correlation_matrix',
                             'correlation_risk_surface',
                             'cross_asset_regime_context',
                             'rates_curve_context',
                             'credit_spread_context',
                             'funding_liquidity_context',
                             'volatility_regime_term_structure',
                             'scenario_stress_ladder',
                             'model_price_sensitivity_grid',
                             'counterparty_liquidity_proxy',
                             'order_flow_imbalance_context',
                             'sweep_block_flow_context',
                             'market_microstructure_liquidity_proxy',
                             'options_chain_surface',
                             'options_flow_sweeps_blocks',
                             'zero_dte_gamma_profile',
                             'iv_skew_term_structure',
                             'put_call_wall_distance',
                             'spread_execution_quality',
                             'one_minute_bars',
                             'tick_proxy_microstructure',
                             'relative_volume',
                             'bid_ask_spread_quality',
                             'opening_range_state',
                             'vwap_deviation',
                             'macro_event_bulletins',
                             'calendar_event_window',
                             'news_source_consensus',
                             'cross_asset_correlation_context'],
 'data_label_contract_version': 'advanced_derivatives_proxy_labels_v1',
 'direct_execution_allowed': False,
 'direct_market_data_available': False,
 'exclude_from_training': True,
 'execution_enabled': False,
 'execution_policy_label': 'research_only_no_execution',
 'freshness_slo_seconds': 1800,
 'label_contract': {},
 'labeling_tags': ['research_only',
                   'collection_only',
                   'proxy_derived',
                   'execution_blocked',
                   'sleeve_family:exotic_derivatives',
                   'sleeve_profile:order_flow_market_microstructure',
                   'data_floor:2500'],
 'lifecycle_state': 'data_collection_only',
 'live_trading_enabled': False,
 'minimum_data_collection_days': 14,
 'minimum_training_observations': 2500,
 'paper_trading_enabled': False,
 'preferred_regimes': ['open_drive_stress', 'event_volatility', 'thin_liquidity'],
 'provider_capability_profile': 'order_flow_microstructure_research_proxy',
 'proxy_data_sources': ['finra_ats_blocks',
                        'exchange_breadth_quotes',
                        'public_sip_quote_proxies',
                        'occ_options_volume_open_interest'],
 'proxy_only_reason': 'Collect order-flow, imbalance, sweep, quote-fade, and spread proxies only; '
                      'no automated microstructure execution.',
 'retention_profile': 'hot_exotic_derivatives_14d_warm_365d',
 'rotation_block_reason': 'data_collection_only_zero_weight',
 'rotation_blocked': True,
 'schwab_direct_inputs': ['listed_equity_etf_quotes',
                          'listed_option_chains',
                          'listed_futures_quotes_when_entitled'],
 'sleeve_family': 'exotic_derivatives',
 'sleeve_profile': 'order_flow_market_microstructure',
 'slot_kind': 'order_flow_market_microstructure_sweep_block_imbalance',
 'slot_label': 'Order Flow/Microstructure Sweep Block Imbalance Bot',
 'slot_objective': 'Collect sweep, block, imbalance, and absorption labels across equities, ETFs, '
                   'options, and futures proxies.',
 'slot_priority': 'high',
 'storage_targets': ['governance/exotic_derivatives',
                     'governance/correlation',
                     'governance/rates',
                     'governance/credit',
                     'exports/exotic_derivatives',
                     'exports/external_context/exotic_derivatives',
                     'governance/order_flow_market_microstructure',
                     'exports/order_flow_market_microstructure',
                     'governance/training_diagnostics',
                     'governance/walk_forward',
                     'data/jsonl_link.sqlite3',
                     'data/bot_channel_queue.sqlite3',
                     'exports/options_flow',
                     'exports/external_context/options_flow',
                     'governance/options_flow',
                     'exports/market_micro',
                     'exports/external_context/market_micro',
                     'governance/intraday',
                     'governance/events',
                     'exports/external_context/macro'],
 'target_functions': ['collect_options_flow_context',
                      'market_correlation_sync',
                      'macro_bulletin',
                      'paper_execution_calibration',
                      'risk_service',
                      'exotic_derivative_context_sync',
                      'market_micro_sync'],
 'trading_enabled': False,
 'training_candidate_after_threshold': True,
 'training_excluded': True,
 'training_threshold_policy': 'eligible_when_minimum_observations_and_days_met'}
BRAIN_REFINERY_V418_ORDER_FLOW_MARKET_MICROSTRUCTURE_SWEEP_BLOCK_IMBALANCE_BOT_SPEC = BOT_SPEC


def describe_bot():
    return describe_registry_backed_bot(BOT_SPEC)


def train_brain():
    return train_registry_backed_bot(BOT_SPEC)


if __name__ == "__main__":
    print(describe_bot())
