"""Registry-backed collection module for Cross-Asset Basis Regression Guard Bot.

Generated by scripts/ops/materialize_core_bot_modules.py

This file exists so the bot is visible and inspectable in PyCharm. The master
registry still controls whether the bot can train, allocate, paper trade, or
live trade.
"""

from __future__ import annotations

try:
    from registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot
except ModuleNotFoundError:
    from core.registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot

BOT_ID = 'brain_refinery_v432_cross_asset_basis_training_basis_regression_guard_bot'
GENERATED_AT_UTC = '2026-05-01T17:00:29.007224+00:00'
BOT_SPEC = {'active': True,
 'allocation_enabled': False,
 'bootstrap_teacher_bot_ids': ['brain_refinery_v187_data_collection_storage_budget_guard',
                               'brain_refinery_v268_resource_aware_expansion_throttle_guard'],
 'bot_id': 'brain_refinery_v432_cross_asset_basis_training_basis_regression_guard_bot',
 'bot_role': 'infrastructure_bot',
 'correlation_dependencies': ['cross_sleeve_exposure_netting',
                              'correlation_cluster_risk',
                              'rates_credit_macro',
                              'futures_curve_context',
                              'options_vol_surface'],
 'correlation_peer_sleeves': ['infrastructure_risk',
                              'synthetic_cdo',
                              'statistical_arbitrage',
                              'options_on_futures',
                              'single_name_options_event',
                              'rates_credit_macro',
                              'futures_rates_curve',
                              'futures_commodity_macro',
                              'pairs_correlation',
                              'volatility',
                              'market_making_liquidity'],
 'data_collection_active': True,
 'data_collection_mode': 'active_observer',
 'data_collection_observations': 0,
 'data_collection_reason': 'active_observer_until_minimum_samples',
 'data_intake_collections': ['registry_slot_metadata',
                             'training_diagnostics',
                             'walk_forward_requalification',
                             'cross_sleeve_correlation_matrix',
                             'correlation_risk_surface',
                             'cross_asset_regime_context',
                             'rates_curve_context',
                             'credit_spread_context',
                             'funding_liquidity_context',
                             'volatility_regime_term_structure',
                             'scenario_stress_ladder',
                             'model_price_sensitivity_grid',
                             'counterparty_liquidity_proxy',
                             'basis_regression_guardrail',
                             'feature_schema_regression_guard',
                             'storage_route_verification',
                             'cross_asset_basis_surface',
                             'etf_futures_basis_context',
                             'fx_crypto_rates_basis_context',
                             'macro_event_bulletins',
                             'calendar_event_window',
                             'news_source_consensus',
                             'cross_asset_correlation_context'],
 'data_label_contract_version': 'advanced_derivatives_proxy_labels_v1',
 'direct_execution_allowed': False,
 'direct_market_data_available': False,
 'exclude_from_training': True,
 'execution_enabled': False,
 'execution_policy_label': 'research_only_no_execution',
 'freshness_slo_seconds': 300,
 'label_contract': {},
 'labeling_tags': ['research_only',
                   'collection_only',
                   'proxy_derived',
                   'execution_blocked',
                   'sleeve_family:exotic_derivatives',
                   'sleeve_profile:cross_asset_basis_training',
                   'data_floor:2500'],
 'lifecycle_state': 'data_collection_only',
 'live_trading_enabled': False,
 'minimum_data_collection_days': 14,
 'minimum_training_observations': 2500,
 'paper_trading_enabled': False,
 'preferred_regimes': ['thin_liquidity', 'macro_repricing', 'risk_off_shock'],
 'provider_capability_profile': 'cross_asset_basis_training_proxy',
 'proxy_data_sources': ['fred_macro_series',
                        'treasury_yield_curve',
                        'sofr_rates',
                        'finra_trace_aggregates',
                        'credit_etf_quotes',
                        'rates_credit_etf_quotes',
                        'finra_ats_blocks',
                        'exchange_breadth_quotes',
                        'public_sip_quote_proxies'],
 'proxy_only_reason': 'Train on ETF/futures/FX/rates/crypto basis relationships through proxy '
                      'inputs before any allocation exposure.',
 'retention_profile': 'hot_exotic_derivatives_14d_warm_365d',
 'rotation_block_reason': 'data_collection_only_zero_weight',
 'rotation_blocked': True,
 'schwab_direct_inputs': ['listed_equity_etf_quotes',
                          'listed_futures_quotes_when_entitled',
                          'rates_credit_etf_quotes'],
 'sleeve_family': 'exotic_derivatives',
 'sleeve_profile': 'cross_asset_basis_training',
 'slot_kind': 'cross_asset_basis_training_basis_regression_guard',
 'slot_label': 'Cross-Asset Basis Regression Guard Bot',
 'slot_objective': 'Guard basis-training labels against stale marks, missing futures entitlement, '
                   'and route/storage schema drift.',
 'slot_priority': 'high',
 'storage_targets': ['governance/exotic_derivatives',
                     'governance/correlation',
                     'governance/rates',
                     'governance/credit',
                     'exports/exotic_derivatives',
                     'exports/external_context/exotic_derivatives',
                     'governance/cross_asset_basis_training',
                     'exports/cross_asset_basis_training',
                     'governance/training_diagnostics',
                     'governance/walk_forward',
                     'data/jsonl_link.sqlite3',
                     'data/bot_channel_queue.sqlite3',
                     'governance/events',
                     'exports/external_context/macro'],
 'target_functions': ['market_correlation_sync',
                      'macro_bulletin',
                      'paper_execution_calibration',
                      'risk_service',
                      'exotic_derivative_context_sync',
                      'supportability_control',
                      'training_quality_control'],
 'trading_enabled': False,
 'training_candidate_after_threshold': True,
 'training_excluded': True,
 'training_threshold_policy': 'eligible_when_minimum_observations_and_days_met'}
BRAIN_REFINERY_V432_CROSS_ASSET_BASIS_TRAINING_BASIS_REGRESSION_GUARD_BOT_SPEC = BOT_SPEC


def describe_bot():
    return describe_registry_backed_bot(BOT_SPEC)


def train_brain():
    return train_registry_backed_bot(BOT_SPEC)


if __name__ == "__main__":
    print(describe_bot())
