"""Registry-backed collection module for Day Trading Low-Float Risk Guard.

Generated by scripts/ops/materialize_core_bot_modules.py

This file exists so the bot is visible and inspectable in PyCharm. The master
registry still controls whether the bot can train, allocate, paper trade, or
live trade.
"""

from __future__ import annotations

try:
    from registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot
except ModuleNotFoundError:
    from core.registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot

BOT_ID = 'brain_refinery_v233_day_trading_low_float_risk_guard'
GENERATED_AT_UTC = '2026-05-02T22:30:58.257676+00:00'
BOT_SPEC = {'active': True,
 'allocation_enabled': False,
 'bootstrap_teacher_bot_ids': ['brain_refinery_v111_slippage_capacity_limiter',
                               'brain_refinery_v225_conservative_liquidity_preservation_guard'],
 'bot_id': 'brain_refinery_v233_day_trading_low_float_risk_guard',
 'bot_role': 'signal_sub_bot',
 'correlation_dependencies': [],
 'correlation_peer_sleeves': [],
 'data_collection_active': True,
 'data_collection_mode': 'active_observer',
 'data_collection_observations': 0,
 'data_collection_reason': 'active_observer_until_minimum_samples',
 'data_intake_collections': ['registry_slot_metadata',
                             'training_diagnostics',
                             'walk_forward_requalification',
                             'one_minute_bars',
                             'tick_proxy_microstructure',
                             'relative_volume',
                             'bid_ask_spread_quality',
                             'opening_range_state',
                             'vwap_deviation',
                             'intraday_tape_speed_context',
                             'intraday_execution_quality',
                             'intraday_liquidity_cliff_state',
                             'opening_auction_state',
                             'closing_auction_state',
                             'vwap_band_context',
                             'first_five_minute_range_state',
                             'ssr_short_sale_restriction_context',
                             'gamma_wall_intraday_context'],
 'data_label_contract_version': '',
 'exclude_from_training': True,
 'execution_enabled': False,
 'execution_policy_label': 'collection_only_no_execution',
 'freshness_slo_seconds': 1800,
 'label_contract': {},
 'labeling_tags': ['research_only',
                   'collection_only',
                   'execution_blocked',
                   'sleeve_family:intraday',
                   'sleeve_profile:day_trading',
                   'data_floor:4000'],
 'lifecycle_state': 'data_collection_only',
 'live_trading_enabled': False,
 'minimum_data_collection_days': 5,
 'minimum_training_observations': 4000,
 'paper_trading_enabled': False,
 'preferred_regimes': ['thin_liquidity', 'event_volatility', 'risk_off_shock'],
 'provider_capability_profile': '',
 'proxy_data_sources': [],
 'proxy_only_reason': '',
 'retention_profile': 'hot_intraday_7d_warm_90d',
 'rotation_block_reason': 'data_collection_only_zero_weight',
 'rotation_blocked': True,
 'schwab_direct_inputs': [],
 'sleeve_family': 'intraday',
 'sleeve_profile': 'day_trading',
 'slot_kind': 'day_trading_risk_guard',
 'slot_label': 'Day Trading Low-Float Risk Guard',
 'slot_objective': 'Down-rank low-float or thin-liquidity day trades when spreads, halts, quote '
                   'gaps, or slippage risk exceed limits.',
 'slot_priority': 'critical',
 'storage_targets': ['governance/training_diagnostics',
                     'governance/walk_forward',
                     'data/jsonl_link.sqlite3',
                     'data/bot_channel_queue.sqlite3',
                     'exports/market_micro',
                     'exports/external_context/market_micro',
                     'governance/intraday',
                     'exports/external_context/intraday'],
 'target_functions': ['market_micro_sync',
                      'paper_execution_calibration',
                      'risk_service',
                      'runtime_throttle_control'],
 'trading_enabled': False,
 'training_candidate_after_threshold': True,
 'training_excluded': True,
 'training_threshold_policy': 'eligible_when_minimum_observations_and_days_met'}
BRAIN_REFINERY_V233_DAY_TRADING_LOW_FLOAT_RISK_GUARD_SPEC = BOT_SPEC


def describe_bot():
    return describe_registry_backed_bot(BOT_SPEC)


def train_brain():
    return train_registry_backed_bot(BOT_SPEC)


if __name__ == "__main__":
    print(describe_bot())
