"""Registry-backed collection module for Reporting Layer Metric Contract Collector.

Generated by scripts/ops/materialize_core_bot_modules.py

This file exists so the bot is visible and inspectable in PyCharm. The master
registry still controls whether the bot can train, allocate, paper trade, or
live trade.
"""

from __future__ import annotations

try:
    from registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot
except ModuleNotFoundError:
    from core.registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot

BOT_ID = 'brain_refinery_v799_reporting_layer_metric_contract_collector_bot'
GENERATED_AT_UTC = '2026-05-02T22:30:58.644395+00:00'
BOT_SPEC = {'active': True,
 'advanced_intelligence_layer_contract': {'bot_intelligence_layer': 'perception',
                                          'capability_pack': 'reporting_layer',
                                          'causal_evidence': 'causal_intervention_ledger_trace',
                                          'contract_version': 'advanced_intelligence_layers_v2',
                                          'critic_guard_bot_id': 'brain_refinery_v802_reporting_layer_pdf_open_regression_guard_bot',
                                          'critic_loop': 'observer_critic_loop_trace',
                                          'cross_pack_memory': 'experience_accumulation_memory_trace',
                                          'global_halt_contract': 'expansion_pressure_aware_soft_cap_before_hard_halt',
                                          'layer_stack': ['perception_data_normalization',
                                                          'reasoning_signal_and_hypothesis_scoring',
                                                          'governance_sleeve_master_aggregation',
                                                          'critic_regression_and_label_validation',
                                                          'capacity_resource_budgeting',
                                                          'memory_experience_accumulation'],
                                          'market_state_graph': 'cross_asset_correlation_context',
                                          'reports_to_sleeve_master_bot_id': 'brain_refinery_v801_reporting_layer_report_suite_master_bot',
                                          'resource_budget': 'compute_capital_allocation_trace',
                                          'semantic_ontology': 'semantic_feature_ontology_trace'},
 'allocation_enabled': False,
 'bootstrap_teacher_bot_ids': ['brain_refinery_v1',
                               'brain_refinery_v59_risk_sentinel',
                               'brain_refinery_v86_risk_budget_allocator_v2'],
 'bot_id': 'brain_refinery_v799_reporting_layer_metric_contract_collector_bot',
 'bot_role': 'infrastructure_sub_bot',
 'capability_pack_contract': {'bot_pack_size': 5,
                              'bot_pack_size_rule': '5_to_15_bots_max',
                              'capacity_check': {'active_bot_floor': 700,
                                                 'compute_guard_mode': 'soft_cap',
                                                 'global_halt_mode': 'soft_cap_and_backpressure_before_hard_halt',
                                                 'queue_policy': 'buffered_jsonl_batching',
                                                 'runtime_control_refresh_seconds': 240,
                                                 'runtime_stability_mode': 'full_force_buffered'},
                              'contract_version': 'intelligence_capability_pack_v1',
                              'dedicated_data_intake': ['report_surface_freshness_contract',
                                                        'paper_performance_graph_contract',
                                                        'system_overview_document_contract',
                                                        'strategy_inventory_pdf_contract',
                                                        'commands_report_validation'],
                              'new_sleeve_or_subsleeve': {'display_name': 'Reporting Layer',
                                                          'sleeve_family': 'reporting',
                                                          'sleeve_profile': 'reporting_layer'},
                              'paper_only_floor': {'allocation_enabled': False,
                                                   'execution_enabled': False,
                                                   'graduation_requires_collection_days': 14,
                                                   'graduation_requires_minimum_observations': 3000,
                                                   'live_trading_enabled': False,
                                                   'paper_trade_lock_required': True},
                              'regression_guard_bot_id': 'brain_refinery_v802_reporting_layer_pdf_open_regression_guard_bot',
                              'sleeve_master_bot_id': 'brain_refinery_v801_reporting_layer_report_suite_master_bot',
                              'storage_retention_rule': {'capture_mode': 'sampled',
                                                         'dedupe_required': True,
                                                         'max_daily_mb_per_bot': 90,
                                                         'retention_profile': 'reports_hot_30d_warm_180d_cold_365d',
                                                         'sample_rate': 0.5,
                                                         'stale_deletion_policy': 'stage_low_value_after_hot_window_and_purge_under_quota_guard',
                                                         'storage_targets': ['exports/reports',
                                                                             'exports/sql_reports',
                                                                             'governance/health/reporting_layer',
                                                                             'governance/report_quality']}},
 'capability_pack_display_name': 'Reporting Layer',
 'capability_pack_slug': 'reporting_layer',
 'capability_pack_version': 'intelligence_capability_pack_v1',
 'correlation_dependencies': ['report_quality_guard', 'commands_hygiene', 'system_summary'],
 'correlation_peer_sleeves': ['model_lifecycle', 'research_automation', 'portfolio_risk_layer'],
 'data_collection_active': True,
 'data_collection_mode': 'active_observer',
 'data_collection_observations': 0,
 'data_collection_reason': 'structured_capability_pack_observer_until_minimum_samples',
 'data_intake_collections': ['report_surface_freshness_contract',
                             'paper_performance_graph_contract',
                             'system_overview_document_contract',
                             'strategy_inventory_pdf_contract',
                             'commands_report_validation'],
 'data_label_contract_version': 'structured_capability_label_v1',
 'direct_execution_allowed': False,
 'direct_market_data_available': False,
 'exclude_from_training': True,
 'execution_enabled': False,
 'execution_policy_label': 'collection_only_paper_locked_no_live_execution',
 'freshness_slo_seconds': 1800,
 'label_contract': {'forbidden_join_modes': ['future_leakage',
                                             'lookahead_join',
                                             'unbounded_raw_feed_join'],
                    'freshness_slo_seconds': 1800,
                    'quality_floor': 0.6,
                    'regression_guard_bot_id': 'brain_refinery_v802_reporting_layer_pdf_open_regression_guard_bot',
                    'required_join_mode': 'point_in_time_only',
                    'required_labels': ['report_type',
                                        'openable_artifact_flag',
                                        'freshness_bucket',
                                        'presentation_ready_grade'],
                    'version': 'structured_capability_label_v1'},
 'labeling_tags': ['research_only',
                   'collection_only',
                   'execution_blocked',
                   'paper_only_floor',
                   'sleeve_family:reporting',
                   'sleeve_profile:reporting_layer',
                   'capability_pack:reporting_layer',
                   'intelligence_layer:perception',
                   'data_floor:3000',
                   'training_after_threshold',
                   'global_halt_aware'],
 'lifecycle_state': 'data_collection_only',
 'live_trading_enabled': False,
 'minimum_data_collection_days': 14,
 'minimum_training_observations': 3000,
 'paper_trading_enabled': False,
 'preferred_regimes': ['daily_review', 'external_review', 'program_head_packet', 'low_pressure'],
 'provider_capability_profile': 'internal_proxy_and_public_context_guarded',
 'proxy_data_sources': ['commands_md',
                        'report_quality_guard',
                        'artifact_freshness_slo',
                        'export_manifest'],
 'proxy_only_reason': 'direct_execution_blocked_until_collection_training_and_paper_gates_clear',
 'retention_profile': 'reports_hot_30d_warm_180d_cold_365d',
 'rotation_block_reason': 'data_collection_only_zero_weight',
 'rotation_blocked': True,
 'schwab_direct_inputs': [],
 'sleeve_family': 'reporting',
 'sleeve_profile': 'reporting_layer',
 'slot_kind': 'intelligence_pack_reporting_layer_metric_contract_collector',
 'slot_label': 'Reporting Layer Metric Contract Collector',
 'slot_objective': 'Collect report freshness, file-open, metric-contract, and graph-readability '
                   'checks.',
 'slot_priority': 'high',
 'storage_targets': ['exports/reports',
                     'exports/sql_reports',
                     'governance/health/reporting_layer',
                     'governance/report_quality'],
 'target_functions': ['report_quality_guard', 'commands_hygiene', 'artifact_freshness_slo'],
 'trading_enabled': False,
 'training_candidate_after_threshold': True,
 'training_excluded': True,
 'training_threshold_policy': 'eligible_when_minimum_observations_and_days_met'}
BRAIN_REFINERY_V799_REPORTING_LAYER_METRIC_CONTRACT_COLLECTOR_BOT_SPEC = BOT_SPEC


def describe_bot():
    return describe_registry_backed_bot(BOT_SPEC)


def train_brain():
    return train_registry_backed_bot(BOT_SPEC)


if __name__ == "__main__":
    print(describe_bot())
