"""Registry-backed collection module for Volatility Regime/Term-Structure Master.

Generated by scripts/ops/materialize_core_bot_modules.py

This file exists so the bot is visible and inspectable in PyCharm. The master
registry still controls whether the bot can train, allocate, paper trade, or
live trade.
"""

from __future__ import annotations

try:
    from registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot
except ModuleNotFoundError:
    from core.registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot

BOT_ID = 'brain_refinery_v249_volatility_regime_term_structure_master'
GENERATED_AT_UTC = '2026-05-01T17:00:28.909761+00:00'
BOT_SPEC = {'active': True,
 'allocation_enabled': False,
 'bootstrap_teacher_bot_ids': ['brain_refinery_v27_term_structure_vol',
                               'brain_refinery_v151_vix_term_structure_event_resolution'],
 'bot_id': 'brain_refinery_v249_volatility_regime_term_structure_master',
 'bot_role': 'signal_sub_bot',
 'correlation_dependencies': [],
 'correlation_peer_sleeves': [],
 'data_collection_active': True,
 'data_collection_mode': 'active_observer',
 'data_collection_observations': 0,
 'data_collection_reason': 'active_observer_until_minimum_samples',
 'data_intake_collections': ['registry_slot_metadata',
                             'training_diagnostics',
                             'walk_forward_requalification',
                             'options_chain_surface',
                             'options_flow_sweeps_blocks',
                             'zero_dte_gamma_profile',
                             'iv_skew_term_structure',
                             'put_call_wall_distance',
                             'spread_execution_quality',
                             'quant_model_feature_surface',
                             'model_price_sensitivity_grid',
                             'state_filter_diagnostics',
                             'tail_risk_surface',
                             'optimization_search_trace',
                             'adaptive_architecture_trace',
                             'execution_microstructure_state',
                             'adversarial_ml_probe_trace',
                             'low_latency_orchestration_trace',
                             'alternative_data_evidence',
                             'privacy_proof_metadata',
                             'gpu_acceleration_profile',
                             'quantum_enhanced_mc_trace',
                             'functional_ito_path_trace',
                             'rough_volatility_fbm_trace',
                             'optimal_transport_bridge_trace',
                             'topological_regime_shape',
                             'neural_sde_trace',
                             'kan_hedging_trace',
                             'vpin_order_flow_toxicity',
                             'signature_path_dna_trace',
                             'hawkes_self_exciting_trace',
                             'signature_market_generator_trace',
                             'mean_field_game_crowd_trace',
                             'physics_informed_constraint_trace',
                             'hurst_persistence_trace',
                             'stochastic_differential_game_trace',
                             'limit_order_book_transformer_trace',
                             'graph_laplacian_tda_diffusion',
                             'agentic_critic_replay_trace',
                             'nonhomogeneous_hmm_trace',
                             'observer_critic_loop_trace',
                             'pin_sde_constraint_trace',
                             'geometric_order_book_transformer_trace',
                             'double_machine_learning_causal_trace',
                             'neuro_symbolic_agent_trace',
                             'cross_modal_embedding_trace',
                             'rlbf_backtracking_feedback_trace',
                             'differentiable_market_simulator_trace',
                             'equivariant_neural_network_trace',
                             'resource_profile',
                             'label_contract_quality',
                             'one_minute_bars',
                             'tick_proxy_microstructure',
                             'relative_volume',
                             'bid_ask_spread_quality',
                             'opening_range_state',
                             'vwap_deviation',
                             'cross_asset_correlation_context'],
 'data_label_contract_version': 'quant_research_labels_v1',
 'direct_execution_allowed': False,
 'direct_market_data_available': False,
 'exclude_from_training': True,
 'execution_enabled': False,
 'execution_policy_label': 'research_only_no_execution',
 'freshness_slo_seconds': 1800,
 'label_contract': {'aux_horizons': ['data_confidence', 'resource_pressure', 'regression_guard'],
                    'contract_version': 'quant_research_labels_v1',
                    'label_family': 'quant_research_control',
                    'primary_horizon': 'research_signal_stability',
                    'required_context': ['quant_model_feature_surface',
                                         'label_contract_quality',
                                         'resource_profile']},
 'labeling_tags': ['research_only',
                   'collection_only',
                   'proxy_derived',
                   'execution_blocked',
                   'sleeve_family:unassigned',
                   'sleeve_profile:unassigned',
                   'data_floor:3000'],
 'lifecycle_state': 'data_collection_only',
 'live_trading_enabled': False,
 'minimum_data_collection_days': 14,
 'minimum_training_observations': 3000,
 'paper_trading_enabled': False,
 'preferred_regimes': ['event_volatility', 'risk_off_shock', 'mixed_transition'],
 'provider_capability_profile': 'research_only_quant_proxy',
 'proxy_data_sources': ['listed_option_surface',
                        'market_context_features',
                        'external_context_quant_model_control',
                        'runtime_decision_history'],
 'proxy_only_reason': 'Quant model bots are research/data-collection only; they enrich features '
                      'and labels but cannot route orders.',
 'retention_profile': 'hot_quant_research_14d_warm_365d',
 'rotation_block_reason': 'data_collection_only_zero_weight',
 'rotation_blocked': True,
 'schwab_direct_inputs': ['listed_equity_etf_quotes', 'listed_option_chains'],
 'sleeve_family': '',
 'sleeve_profile': '',
 'slot_kind': 'volatility_regime_signal',
 'slot_label': 'Volatility Regime/Term-Structure Master',
 'slot_objective': 'Classify volatility regimes using VIX term structure, realized/implied spread, '
                   'event risk, and cross-asset stress.',
 'slot_priority': 'high',
 'storage_targets': ['governance/training_diagnostics',
                     'governance/walk_forward',
                     'data/jsonl_link.sqlite3',
                     'data/bot_channel_queue.sqlite3',
                     'exports/options_flow',
                     'exports/external_context/options_flow',
                     'governance/options_flow',
                     'governance/quant_models',
                     'governance/label_contracts',
                     'governance/resource',
                     'exports/quant_models',
                     'exports/external_context/quant_model_control',
                     'exports/market_micro',
                     'exports/external_context/market_micro',
                     'governance/intraday'],
 'target_functions': ['collect_options_flow_context',
                      'market_micro_sync',
                      'market_correlation_sync',
                      'risk_service'],
 'trading_enabled': False,
 'training_candidate_after_threshold': True,
 'training_excluded': True,
 'training_threshold_policy': 'eligible_when_minimum_observations_and_days_met'}
BRAIN_REFINERY_V249_VOLATILITY_REGIME_TERM_STRUCTURE_MASTER_SPEC = BOT_SPEC


def describe_bot():
    return describe_registry_backed_bot(BOT_SPEC)


def train_brain():
    return train_registry_backed_bot(BOT_SPEC)


if __name__ == "__main__":
    print(describe_bot())
