"""Registry-backed collection module for Dividend Sector Income Rotation Bot.

Generated by scripts/ops/materialize_core_bot_modules.py

This file exists so the bot is visible and inspectable in PyCharm. The master
registry still controls whether the bot can train, allocate, paper trade, or
live trade.
"""

from __future__ import annotations

try:
    from registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot
except ModuleNotFoundError:
    from core.registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot

BOT_ID = 'brain_refinery_v637_dividend_sector_income_rotation_bot'
GENERATED_AT_UTC = '2026-05-02T22:30:58.518666+00:00'
BOT_SPEC = {'active': True,
 'allocation_enabled': False,
 'bootstrap_teacher_bot_ids': ['brain_refinery_v213_dividend_aristocrat_rotation_bot',
                               'brain_refinery_v113_sector_breadth_rotation_fallback'],
 'bot_id': 'brain_refinery_v637_dividend_sector_income_rotation_bot',
 'bot_role': 'signal_sub_bot',
 'correlation_dependencies': [],
 'correlation_peer_sleeves': [],
 'data_collection_active': True,
 'data_collection_mode': 'active_observer',
 'data_collection_observations': 0,
 'data_collection_reason': 'active_observer_until_minimum_samples',
 'data_intake_collections': ['registry_slot_metadata',
                             'training_diagnostics',
                             'walk_forward_requalification',
                             'dividend_calendar_context',
                             'dividend_drip_state',
                             'payout_history_state',
                             'dividend_cashflow_quality',
                             'qualified_dividend_tax_window',
                             'income_sleeve_total_return_context',
                             'sector_factor_context',
                             'extended_quant_context',
                             'cross_asset_correlation_context'],
 'data_label_contract_version': '',
 'direct_execution_allowed': None,
 'direct_market_data_available': None,
 'exclude_from_training': True,
 'execution_enabled': False,
 'execution_policy_label': 'collection_only_no_execution',
 'freshness_slo_seconds': 1800,
 'label_contract': {},
 'labeling_tags': ['research_only',
                   'collection_only',
                   'execution_blocked',
                   'sleeve_family:dividend',
                   'sleeve_profile:dividend_income',
                   'data_floor:1000'],
 'lifecycle_state': 'data_collection_only',
 'live_trading_enabled': False,
 'minimum_data_collection_days': 7,
 'minimum_training_observations': 1000,
 'paper_trading_enabled': False,
 'preferred_regimes': ['slow_rotation', 'mixed_transition', 'risk_off_trend'],
 'provider_capability_profile': '',
 'proxy_data_sources': [],
 'proxy_only_reason': '',
 'retention_profile': 'standard_candidate_30d_warm_180d',
 'rotation_block_reason': 'data_collection_only_zero_weight',
 'rotation_blocked': True,
 'schwab_direct_inputs': [],
 'sleeve_family': 'dividend',
 'sleeve_profile': 'dividend_income',
 'slot_kind': 'dividend_income_signal',
 'slot_label': 'Dividend Sector Income Rotation Bot',
 'slot_objective': 'Rotate dividend exposure across utilities, staples, healthcare, energy, REITs, '
                   'financials, and quality tech as rates and breadth shift.',
 'slot_priority': 'medium',
 'storage_targets': ['governance/training_diagnostics',
                     'governance/walk_forward',
                     'data/jsonl_link.sqlite3',
                     'data/bot_channel_queue.sqlite3',
                     'governance/dividend',
                     'exports/external_context/dividend',
                     'exports/dividend',
                     'exports/external_context/extended_quant'],
 'target_functions': ['market_correlation_sync',
                      'collect_extended_quant_context',
                      'portfolio_allocator',
                      'regime_control_plane'],
 'trading_enabled': False,
 'training_candidate_after_threshold': True,
 'training_excluded': True,
 'training_threshold_policy': 'eligible_when_minimum_observations_and_days_met'}
BRAIN_REFINERY_V637_DIVIDEND_SECTOR_INCOME_ROTATION_BOT_SPEC = BOT_SPEC


def describe_bot():
    return describe_registry_backed_bot(BOT_SPEC)


def train_brain():
    return train_registry_backed_bot(BOT_SPEC)


if __name__ == "__main__":
    print(describe_bot())
