"""Registry-backed collection module for Cross-Asset Basis Crypto/ETF Basis Bot.

Generated by scripts/ops/materialize_core_bot_modules.py

This file exists so the bot is visible and inspectable in PyCharm. The master
registry still controls whether the bot can train, allocate, paper trade, or
live trade.
"""

from __future__ import annotations

try:
    from registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot
except ModuleNotFoundError:
    from core.registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot

BOT_ID = 'brain_refinery_v430_cross_asset_basis_training_crypto_etf_basis_bot'
GENERATED_AT_UTC = '2026-05-02T22:30:58.357540+00:00'
BOT_SPEC = {'active': True,
 'allocation_enabled': False,
 'bootstrap_teacher_bot_ids': ['brain_refinery_v283_crypto_futures_basis_divergence_bot',
                               'brain_refinery_v285_crypto_etf_spot_future_confirmation_bot'],
 'bot_id': 'brain_refinery_v430_cross_asset_basis_training_crypto_etf_basis_bot',
 'bot_role': 'crypto_sub_bot',
 'correlation_dependencies': ['cross_sleeve_exposure_netting',
                              'correlation_cluster_risk',
                              'rates_credit_macro',
                              'futures_curve_context',
                              'options_vol_surface'],
 'correlation_peer_sleeves': ['crypto_futures_basis',
                              'crypto_spot',
                              'pairs_correlation',
                              'options_on_futures',
                              'single_name_options_event',
                              'rates_credit_macro',
                              'futures_rates_curve',
                              'futures_commodity_macro',
                              'volatility',
                              'market_making_liquidity'],
 'data_collection_active': True,
 'data_collection_mode': 'active_observer',
 'data_collection_observations': 0,
 'data_collection_reason': 'active_observer_until_minimum_samples',
 'data_intake_collections': ['registry_slot_metadata',
                             'training_diagnostics',
                             'walk_forward_requalification',
                             'cross_sleeve_correlation_matrix',
                             'correlation_risk_surface',
                             'cross_asset_regime_context',
                             'rates_curve_context',
                             'credit_spread_context',
                             'funding_liquidity_context',
                             'volatility_regime_term_structure',
                             'scenario_stress_ladder',
                             'model_price_sensitivity_grid',
                             'counterparty_liquidity_proxy',
                             'crypto_etf_basis_context',
                             'cross_asset_basis_surface',
                             'crypto_cross_asset_beta',
                             'etf_futures_basis_context',
                             'fx_crypto_rates_basis_context',
                             'macro_event_bulletins',
                             'calendar_event_window',
                             'news_source_consensus',
                             'crypto_liquidity_context',
                             'cross_asset_correlation_context'],
 'data_label_contract_version': 'advanced_derivatives_proxy_labels_v1',
 'direct_execution_allowed': False,
 'direct_market_data_available': False,
 'exclude_from_training': True,
 'execution_enabled': False,
 'execution_policy_label': 'research_only_no_execution',
 'freshness_slo_seconds': 1800,
 'label_contract': {},
 'labeling_tags': ['research_only',
                   'collection_only',
                   'proxy_derived',
                   'execution_blocked',
                   'sleeve_family:exotic_derivatives',
                   'sleeve_profile:cross_asset_basis_training',
                   'data_floor:2500'],
 'lifecycle_state': 'data_collection_only',
 'live_trading_enabled': False,
 'minimum_data_collection_days': 14,
 'minimum_training_observations': 2500,
 'paper_trading_enabled': False,
 'preferred_regimes': ['event_volatility', 'risk_off_shock', 'mixed_transition'],
 'provider_capability_profile': 'cross_asset_basis_training_proxy',
 'proxy_data_sources': ['fred_macro_series',
                        'treasury_yield_curve',
                        'sofr_rates',
                        'finra_trace_aggregates',
                        'credit_etf_quotes',
                        'rates_credit_etf_quotes',
                        'finra_ats_blocks',
                        'exchange_breadth_quotes',
                        'public_sip_quote_proxies'],
 'proxy_only_reason': 'Train on ETF/futures/FX/rates/crypto basis relationships through proxy '
                      'inputs before any allocation exposure.',
 'retention_profile': 'hot_exotic_derivatives_14d_warm_365d',
 'rotation_block_reason': 'data_collection_only_zero_weight',
 'rotation_blocked': True,
 'schwab_direct_inputs': ['listed_equity_etf_quotes',
                          'listed_futures_quotes_when_entitled',
                          'rates_credit_etf_quotes'],
 'sleeve_family': 'exotic_derivatives',
 'sleeve_profile': 'cross_asset_basis_training',
 'slot_kind': 'cross_asset_basis_training_crypto_etf_basis',
 'slot_label': 'Cross-Asset Basis Crypto/ETF Basis Bot',
 'slot_objective': 'Observe crypto spot, ETF, equity proxy, and futures basis relationships.',
 'slot_priority': 'medium',
 'storage_targets': ['governance/exotic_derivatives',
                     'governance/correlation',
                     'governance/rates',
                     'governance/credit',
                     'exports/exotic_derivatives',
                     'exports/external_context/exotic_derivatives',
                     'governance/cross_asset_basis_training',
                     'exports/cross_asset_basis_training',
                     'governance/training_diagnostics',
                     'governance/walk_forward',
                     'data/jsonl_link.sqlite3',
                     'data/bot_channel_queue.sqlite3',
                     'governance/events',
                     'exports/external_context/macro',
                     'exports/external_context/crypto_market'],
 'target_functions': ['market_correlation_sync',
                      'macro_bulletin',
                      'paper_execution_calibration',
                      'risk_service',
                      'exotic_derivative_context_sync',
                      'crypto_market_sync'],
 'trading_enabled': False,
 'training_candidate_after_threshold': True,
 'training_excluded': True,
 'training_threshold_policy': 'eligible_when_minimum_observations_and_days_met'}
BRAIN_REFINERY_V430_CROSS_ASSET_BASIS_TRAINING_CRYPTO_ETF_BASIS_BOT_SPEC = BOT_SPEC


def describe_bot():
    return describe_registry_backed_bot(BOT_SPEC)


def train_brain():
    return train_registry_backed_bot(BOT_SPEC)


if __name__ == "__main__":
    print(describe_bot())
