"""Registry-backed collection module for Options IV/Realized Spread Breakout.

Generated by scripts/ops/materialize_core_bot_modules.py

This file exists so the bot is visible and inspectable in PyCharm. The master
registry still controls whether the bot can train, allocate, paper trade, or
live trade.
"""

from __future__ import annotations

try:
    from registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot
except ModuleNotFoundError:
    from core.registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot

BOT_ID = 'brain_refinery_v184_options_iv_realized_spread_breakout'
GENERATED_AT_UTC = '2026-05-01T17:00:28.878198+00:00'
BOT_SPEC = {'active': True,
 'allocation_enabled': False,
 'bootstrap_teacher_bot_ids': ['brain_refinery_v27_term_structure_vol',
                               'brain_refinery_v151_vix_term_structure_event_resolution'],
 'bot_id': 'brain_refinery_v184_options_iv_realized_spread_breakout',
 'bot_role': 'options_sub_bot',
 'correlation_dependencies': [],
 'correlation_peer_sleeves': [],
 'data_collection_active': True,
 'data_collection_mode': 'active_observer',
 'data_collection_observations': 69,
 'data_collection_reason': 'active_observer_until_minimum_samples',
 'data_intake_collections': ['registry_slot_metadata',
                             'training_diagnostics',
                             'walk_forward_requalification',
                             'options_chain_surface',
                             'options_flow_sweeps_blocks',
                             'zero_dte_gamma_profile',
                             'iv_skew_term_structure',
                             'put_call_wall_distance',
                             'spread_execution_quality',
                             'one_minute_bars',
                             'tick_proxy_microstructure',
                             'relative_volume',
                             'bid_ask_spread_quality',
                             'opening_range_state',
                             'vwap_deviation',
                             'macro_event_bulletins',
                             'calendar_event_window',
                             'news_source_consensus'],
 'data_label_contract_version': '',
 'exclude_from_training': True,
 'execution_enabled': False,
 'execution_policy_label': 'collection_only_no_execution',
 'freshness_slo_seconds': 1800,
 'label_contract': {},
 'labeling_tags': ['research_only',
                   'collection_only',
                   'execution_blocked',
                   'sleeve_family:unassigned',
                   'sleeve_profile:unassigned',
                   'data_floor:1500'],
 'lifecycle_state': 'data_collection_only',
 'live_trading_enabled': False,
 'minimum_data_collection_days': 7,
 'minimum_training_observations': 1500,
 'paper_trading_enabled': False,
 'preferred_regimes': ['event_volatility', 'open_drive_stress', 'fragile_transition'],
 'provider_capability_profile': '',
 'proxy_data_sources': [],
 'proxy_only_reason': '',
 'retention_profile': 'hot_options_14d_warm_180d',
 'rotation_block_reason': 'data_collection_only_zero_weight',
 'rotation_blocked': True,
 'schwab_direct_inputs': [],
 'sleeve_family': '',
 'sleeve_profile': '',
 'slot_kind': 'vol_surface_overlay',
 'slot_label': 'Options IV/Realized Spread Breakout',
 'slot_objective': 'Detect when implied volatility is underpricing realized intraday movement and '
                   'event risk is still expanding.',
 'slot_priority': 'high',
 'storage_targets': ['governance/training_diagnostics',
                     'governance/walk_forward',
                     'data/jsonl_link.sqlite3',
                     'data/bot_channel_queue.sqlite3',
                     'exports/options_flow',
                     'exports/external_context/options_flow',
                     'governance/options_flow',
                     'exports/market_micro',
                     'exports/external_context/market_micro',
                     'governance/intraday',
                     'governance/events',
                     'exports/external_context/macro'],
 'target_functions': ['collect_options_flow_context',
                      'market_micro_sync',
                      'macro_bulletin',
                      'risk_service'],
 'trading_enabled': False,
 'training_candidate_after_threshold': True,
 'training_excluded': True,
 'training_threshold_policy': 'eligible_when_minimum_observations_and_days_met'}
BRAIN_REFINERY_V184_OPTIONS_IV_REALIZED_SPREAD_BREAKOUT_SPEC = BOT_SPEC


def describe_bot():
    return describe_registry_backed_bot(BOT_SPEC)


def train_brain():
    return train_registry_backed_bot(BOT_SPEC)


if __name__ == "__main__":
    print(describe_bot())
