"""Registry-backed collection module for Futures Index Open-Drive Mapper.

Generated by scripts/ops/materialize_core_bot_modules.py

This file exists so the bot is visible and inspectable in PyCharm. The master
registry still controls whether the bot can train, allocate, paper trade, or
live trade.
"""

from __future__ import annotations

try:
    from registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot
except ModuleNotFoundError:
    from core.registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot

BOT_ID = 'brain_refinery_v189_futures_index_open_drive_mapper'
GENERATED_AT_UTC = '2026-05-02T22:30:58.238092+00:00'
BOT_SPEC = {'active': True,
 'allocation_enabled': False,
 'bootstrap_teacher_bot_ids': ['brain_refinery_v172_intraday_futures_lead_lag_arbitrage',
                               'brain_refinery_v104_futures_event_followthrough'],
 'bot_id': 'brain_refinery_v189_futures_index_open_drive_mapper',
 'bot_role': 'futures_sub_bot',
 'correlation_dependencies': [],
 'correlation_peer_sleeves': [],
 'data_collection_active': True,
 'data_collection_mode': 'active_observer',
 'data_collection_observations': 0,
 'data_collection_reason': 'active_observer_until_minimum_samples',
 'data_intake_collections': ['registry_slot_metadata',
                             'training_diagnostics',
                             'walk_forward_requalification',
                             'one_minute_bars',
                             'tick_proxy_microstructure',
                             'relative_volume',
                             'bid_ask_spread_quality',
                             'opening_range_state',
                             'vwap_deviation',
                             'cross_asset_correlation_context'],
 'data_label_contract_version': '',
 'exclude_from_training': True,
 'execution_enabled': False,
 'execution_policy_label': 'collection_only_no_execution',
 'freshness_slo_seconds': 1800,
 'label_contract': {},
 'labeling_tags': ['research_only',
                   'collection_only',
                   'execution_blocked',
                   'sleeve_family:unassigned',
                   'sleeve_profile:unassigned',
                   'data_floor:1000'],
 'lifecycle_state': 'data_collection_only',
 'live_trading_enabled': False,
 'minimum_data_collection_days': 7,
 'minimum_training_observations': 1000,
 'paper_trading_enabled': False,
 'preferred_regimes': ['open_drive_stress', 'event_volatility', 'mixed_transition'],
 'provider_capability_profile': '',
 'proxy_data_sources': [],
 'proxy_only_reason': '',
 'retention_profile': 'standard_candidate_30d_warm_180d',
 'rotation_block_reason': 'data_collection_only_zero_weight',
 'rotation_blocked': True,
 'schwab_direct_inputs': [],
 'sleeve_family': '',
 'sleeve_profile': '',
 'slot_kind': 'index_futures_signal',
 'slot_label': 'Futures Index Open-Drive Mapper',
 'slot_objective': 'Map /ES, /NQ, /YM, and /RTY open-drive behavior against ETF breadth, volume, '
                   'and overnight inventory before equity cash catches up.',
 'slot_priority': 'high',
 'storage_targets': ['governance/training_diagnostics',
                     'governance/walk_forward',
                     'data/jsonl_link.sqlite3',
                     'data/bot_channel_queue.sqlite3',
                     'exports/market_micro',
                     'exports/external_context/market_micro',
                     'governance/intraday'],
 'target_functions': ['market_micro_sync',
                      'market_correlation_sync',
                      'feed_refresh',
                      'regime_control_plane'],
 'trading_enabled': False,
 'training_candidate_after_threshold': True,
 'training_excluded': True,
 'training_threshold_policy': 'eligible_when_minimum_observations_and_days_met'}
BRAIN_REFINERY_V189_FUTURES_INDEX_OPEN_DRIVE_MAPPER_SPEC = BOT_SPEC


def describe_bot():
    return describe_registry_backed_bot(BOT_SPEC)


def train_brain():
    return train_registry_backed_bot(BOT_SPEC)


if __name__ == "__main__":
    print(describe_bot())
