"""Registry-backed collection module for Macro Liquidity Drain/Refill Bot.

Generated by scripts/ops/materialize_core_bot_modules.py

This file exists so the bot is visible and inspectable in PyCharm. The master
registry still controls whether the bot can train, allocate, paper trade, or
live trade.
"""

from __future__ import annotations

try:
    from registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot
except ModuleNotFoundError:
    from core.registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot

BOT_ID = 'brain_refinery_v308_macro_liquidity_drain_refill_bot'
GENERATED_AT_UTC = '2026-05-01T17:00:28.935954+00:00'
BOT_SPEC = {'active': True,
 'allocation_enabled': False,
 'bootstrap_teacher_bot_ids': ['brain_refinery_v127_dollar_funding_fx_stress_relay',
                               'brain_refinery_v260_crypto_stablecoin_liquidity_impulse_bot'],
 'bot_id': 'brain_refinery_v308_macro_liquidity_drain_refill_bot',
 'bot_role': 'signal_sub_bot',
 'correlation_dependencies': [],
 'correlation_peer_sleeves': [],
 'data_collection_active': True,
 'data_collection_mode': 'active_observer',
 'data_collection_observations': 0,
 'data_collection_reason': 'active_observer_until_minimum_samples',
 'data_intake_collections': ['registry_slot_metadata',
                             'training_diagnostics',
                             'walk_forward_requalification',
                             'macro_event_bulletins',
                             'calendar_event_window',
                             'news_source_consensus',
                             'crypto_liquidity_context',
                             'crypto_cross_asset_beta',
                             'fx_rates_context',
                             'usd_funding_stress'],
 'data_label_contract_version': '',
 'exclude_from_training': True,
 'execution_enabled': False,
 'execution_policy_label': 'collection_only_no_execution',
 'freshness_slo_seconds': 1800,
 'label_contract': {},
 'labeling_tags': ['research_only',
                   'collection_only',
                   'execution_blocked',
                   'sleeve_family:unassigned',
                   'sleeve_profile:unassigned',
                   'data_floor:1000'],
 'lifecycle_state': 'data_collection_only',
 'live_trading_enabled': False,
 'minimum_data_collection_days': 7,
 'minimum_training_observations': 1000,
 'paper_trading_enabled': False,
 'preferred_regimes': ['macro_repricing', 'fragile_transition', 'risk_off_trend'],
 'provider_capability_profile': '',
 'proxy_data_sources': [],
 'proxy_only_reason': '',
 'retention_profile': 'standard_candidate_30d_warm_180d',
 'rotation_block_reason': 'data_collection_only_zero_weight',
 'rotation_blocked': True,
 'schwab_direct_inputs': [],
 'sleeve_family': '',
 'sleeve_profile': '',
 'slot_kind': 'macro_liquidity_signal',
 'slot_label': 'Macro Liquidity Drain/Refill Bot',
 'slot_objective': 'Track liquidity drain/refill context through dollar funding, rates, credit, '
                   'crypto stablecoins, and equity breadth.',
 'slot_priority': 'medium',
 'storage_targets': ['governance/training_diagnostics',
                     'governance/walk_forward',
                     'data/jsonl_link.sqlite3',
                     'data/bot_channel_queue.sqlite3',
                     'governance/events',
                     'exports/external_context/macro',
                     'exports/external_context/crypto_market',
                     'exports/external_context/fx_market'],
 'target_functions': ['macro_bulletin',
                      'fx_market_sync',
                      'crypto_market_sync',
                      'portfolio_allocator'],
 'trading_enabled': False,
 'training_candidate_after_threshold': True,
 'training_excluded': True,
 'training_threshold_policy': 'eligible_when_minimum_observations_and_days_met'}
BRAIN_REFINERY_V308_MACRO_LIQUIDITY_DRAIN_REFILL_BOT_SPEC = BOT_SPEC


def describe_bot():
    return describe_registry_backed_bot(BOT_SPEC)


def train_brain():
    return train_registry_backed_bot(BOT_SPEC)


if __name__ == "__main__":
    print(describe_bot())
