"""Registry-backed collection module for Structured Products Principal Protection Rate Bot.

Generated by scripts/ops/materialize_core_bot_modules.py

This file exists so the bot is visible and inspectable in PyCharm. The master
registry still controls whether the bot can train, allocate, paper trade, or
live trade.
"""

from __future__ import annotations

try:
    from registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot
except ModuleNotFoundError:
    from core.registry_backed_collection_bot import describe_registry_backed_bot, train_registry_backed_bot

BOT_ID = 'brain_refinery_v346_structured_products_principal_protection_rate_bot'
GENERATED_AT_UTC = '2026-05-02T22:30:58.309456+00:00'
BOT_SPEC = {'active': True,
 'allocation_enabled': False,
 'bootstrap_teacher_bot_ids': ['brain_refinery_v219_conservative_tbill_cash_parking_bot',
                               'brain_refinery_v305_bond_credit_quality_rotation_bot'],
 'bot_id': 'brain_refinery_v346_structured_products_principal_protection_rate_bot',
 'bot_role': 'options_sub_bot',
 'correlation_dependencies': ['cross_sleeve_exposure_netting',
                              'correlation_cluster_risk',
                              'rates_credit_macro',
                              'futures_curve_context',
                              'options_vol_surface'],
 'correlation_peer_sleeves': ['rates_credit_macro',
                              'cash_rotation_tactical',
                              'options_on_futures',
                              'single_name_options_event',
                              'futures_rates_curve',
                              'futures_commodity_macro',
                              'pairs_correlation',
                              'volatility',
                              'market_making_liquidity'],
 'data_collection_active': True,
 'data_collection_mode': 'active_observer',
 'data_collection_observations': 0,
 'data_collection_reason': 'active_observer_until_minimum_samples',
 'data_intake_collections': ['registry_slot_metadata',
                             'training_diagnostics',
                             'walk_forward_requalification',
                             'cross_sleeve_correlation_matrix',
                             'correlation_risk_surface',
                             'cross_asset_regime_context',
                             'rates_curve_context',
                             'credit_spread_context',
                             'funding_liquidity_context',
                             'volatility_regime_term_structure',
                             'scenario_stress_ladder',
                             'model_price_sensitivity_grid',
                             'counterparty_liquidity_proxy',
                             'principal_protection_payoff_ladder',
                             'issuer_credit_proxy',
                             'duration_beta_context',
                             'options_chain_surface',
                             'options_flow_sweeps_blocks',
                             'zero_dte_gamma_profile',
                             'iv_skew_term_structure',
                             'put_call_wall_distance',
                             'spread_execution_quality',
                             'autocall_barrier_ladder',
                             'structured_payoff_ladder',
                             'macro_event_bulletins',
                             'calendar_event_window',
                             'news_source_consensus',
                             'cross_asset_correlation_context'],
 'data_label_contract_version': 'advanced_derivatives_proxy_labels_v1',
 'direct_execution_allowed': False,
 'direct_market_data_available': False,
 'exclude_from_training': True,
 'execution_enabled': False,
 'execution_policy_label': 'research_only_no_execution',
 'freshness_slo_seconds': 1800,
 'label_contract': {},
 'labeling_tags': ['research_only',
                   'collection_only',
                   'proxy_derived',
                   'execution_blocked',
                   'sleeve_family:exotic_derivatives',
                   'sleeve_profile:structured_products',
                   'data_floor:2500'],
 'lifecycle_state': 'data_collection_only',
 'live_trading_enabled': False,
 'minimum_data_collection_days': 14,
 'minimum_training_observations': 2500,
 'paper_trading_enabled': False,
 'preferred_regimes': ['macro_repricing', 'low_volatility', 'mixed_transition'],
 'provider_capability_profile': 'payoff_barrier_credit_proxy',
 'proxy_data_sources': ['sec_edgar_filings',
                        'structured_note_prospectus_text',
                        'finra_trace_aggregates',
                        'credit_etf_quotes',
                        'rates_credit_etf_quotes',
                        'occ_options_volume_open_interest'],
 'proxy_only_reason': 'Use issuer filings, credit proxies, listed options, and '
                      'buffered/covered-call ETP analogs.',
 'retention_profile': 'hot_exotic_derivatives_14d_warm_365d',
 'rotation_block_reason': 'data_collection_only_zero_weight',
 'rotation_blocked': True,
 'schwab_direct_inputs': ['listed_equity_etf_quotes', 'listed_option_chains'],
 'sleeve_family': 'exotic_derivatives',
 'sleeve_profile': 'structured_products',
 'slot_kind': 'structured_products_principal_protection_rate',
 'slot_label': 'Structured Products Principal Protection Rate Bot',
 'slot_objective': 'Track principal-protected note proxies through rates, duration, credit, and '
                   'participation-cap conditions.',
 'slot_priority': 'medium',
 'storage_targets': ['governance/exotic_derivatives',
                     'governance/correlation',
                     'governance/rates',
                     'governance/credit',
                     'exports/exotic_derivatives',
                     'exports/external_context/exotic_derivatives',
                     'governance/structured_products',
                     'exports/structured_products',
                     'governance/training_diagnostics',
                     'governance/walk_forward',
                     'data/jsonl_link.sqlite3',
                     'data/bot_channel_queue.sqlite3',
                     'exports/options_flow',
                     'exports/external_context/options_flow',
                     'governance/options_flow',
                     'governance/events',
                     'exports/external_context/macro'],
 'target_functions': ['collect_options_flow_context',
                      'market_correlation_sync',
                      'macro_bulletin',
                      'paper_execution_calibration',
                      'risk_service',
                      'exotic_derivative_context_sync'],
 'trading_enabled': False,
 'training_candidate_after_threshold': True,
 'training_excluded': True,
 'training_threshold_policy': 'eligible_when_minimum_observations_and_days_met'}
BRAIN_REFINERY_V346_STRUCTURED_PRODUCTS_PRINCIPAL_PROTECTION_RATE_BOT_SPEC = BOT_SPEC


def describe_bot():
    return describe_registry_backed_bot(BOT_SPEC)


def train_brain():
    return train_registry_backed_bot(BOT_SPEC)


if __name__ == "__main__":
    print(describe_bot())
