#!/bin/zsh
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PYTHON_BIN="$PROJECT_ROOT/.venv312/bin/python"
STAMP="$(date -u +%Y%m%d_%H%M%S)"
RETRAIN_LOG_DIR="$PROJECT_ROOT/governance/training_diagnostics/retrain_launch_logs"
RUN_TAG="retrain_daily_small_${STAMP}_$$"
RUN_LOG="$RETRAIN_LOG_DIR/${RUN_TAG}.log"

mkdir -p "$RETRAIN_LOG_DIR"

export RETRAIN_TRIGGER_SOURCE="launchd_daily_small"
export RETRAIN_TRIGGER_LABEL="com.dankingsley.retrain.daily_small"
export RETRAIN_TRIGGER_CONTEXT="scheduled_daily_small"
export RETRAIN_LAUNCH_LOG_PATH="$RUN_LOG"

exec > >(tee -a "$RUN_LOG") 2>&1

cd "$PROJECT_ROOT"

echo "[RetrainLaunch] source=$RETRAIN_TRIGGER_SOURCE label=$RETRAIN_TRIGGER_LABEL log=$RUN_LOG"

"$PYTHON_BIN" "$PROJECT_ROOT/scripts/resource_guard.py" || {
  echo "retrain skipped by resource_guard"
  exit 0
}

export RETRAIN_ACTIVE_ONLY=1
export RETRAIN_MAX_TARGETS=12
export RETRAIN_MIN_MODEL_AGE_HOURS=18
export RETRAIN_PROFILE="${RETRAIN_PROFILE:-fast_daytime}"
export RETRAIN_AFTER_HOURS_ONLY=1
export RETRAIN_RETIRE_PERSISTENT_LOSERS=1
export RETRAIN_RETIRE_APPLY=1
export RETRAIN_RETIRE_MIN_FAIL_DAYS=5
export RETRAIN_RETIRE_MIN_NO_IMPROVEMENT_STREAK=2
export RETRAIN_RETIRE_MAX_PER_RUN=6
export RETRAIN_REGIME_BALANCE=1
export RETRAIN_PROMOTION_BOTTLENECK_PRIORITY=1
export RETRAIN_MIN_FREE_PCT="${RETRAIN_MIN_FREE_PCT:-18}"
export RETRAIN_MAX_SWAP_GB="${RETRAIN_MAX_SWAP_GB:-2.5}"
export RETRAIN_ADAPTIVE_SWAP_STEP_GB="${RETRAIN_ADAPTIVE_SWAP_STEP_GB:-0.6}"
export RETRAIN_ADAPTIVE_SWAP_MAX_GB="${RETRAIN_ADAPTIVE_SWAP_MAX_GB:-6.0}"
export RETRAIN_SWAP_RELAX_FREE_PCT="${RETRAIN_SWAP_RELAX_FREE_PCT:-38}"
export RETRAIN_SWAP_RELAX_AVAILABLE_PCT="${RETRAIN_SWAP_RELAX_AVAILABLE_PCT:-55}"
export RETRAIN_MEMORY_MAX_WAIT_SECONDS="${RETRAIN_MEMORY_MAX_WAIT_SECONDS:-300}"
export RETRAIN_MEMORY_POLL_SECONDS="${RETRAIN_MEMORY_POLL_SECONDS:-15}"
export RETRAIN_MAX_DATA_DIVERGENCE_SPREAD="${RETRAIN_MAX_DATA_DIVERGENCE_SPREAD:-0.10}"
export RETRAIN_COUNTERFACTUAL_REPLAY="${RETRAIN_COUNTERFACTUAL_REPLAY:-0}"
export RETRAIN_PAPER_HARD_EXAMPLE_PACK="${RETRAIN_PAPER_HARD_EXAMPLE_PACK:-0}"
export RETRAIN_REQUIRE_SAMPLE_QUOTAS="${RETRAIN_REQUIRE_SAMPLE_QUOTAS:-0}"
export RETRAIN_NEW_BOT_BOOST="${RETRAIN_NEW_BOT_BOOST:-0}"
export RETRAIN_BUILD_RUNTIME_TRAINING_SNAPSHOT="${RETRAIN_BUILD_RUNTIME_TRAINING_SNAPSHOT:-1}"
export RUNTIME_TRAIN_USE_SNAPSHOT="${RUNTIME_TRAIN_USE_SNAPSHOT:-1}"
export RUNTIME_TRAIN_PREFER_SQLITE="${RUNTIME_TRAIN_PREFER_SQLITE:-1}"
export RUNTIME_TRAIN_FAST_FAIL_ZERO_SAMPLE_ATTEMPTS="${RUNTIME_TRAIN_FAST_FAIL_ZERO_SAMPLE_ATTEMPTS:-2}"
export TRADE_BEHAVIOR_CLASS_BALANCE_CAP=5.5
export TRADE_BEHAVIOR_NEUTRAL_WEIGHT_FLOOR=1.35
export TRADE_BEHAVIOR_POSITIVE_WEIGHT_FLOOR=2.00
export TRADE_BEHAVIOR_NEGATIVE_WEIGHT_CAP=0.85
export TRADE_BEHAVIOR_REGIME_BALANCE_CAP=3.0
export TRADE_BEHAVIOR_REQUIRE_WALK_FORWARD_OK=1
export TRADE_BEHAVIOR_STRICT_PROMOTION_GATE=1
export TRADE_BEHAVIOR_STRICT="${TRADE_BEHAVIOR_STRICT:-1}"
export TRADE_BEHAVIOR_ROLLBACK_REQUIRE_SCHEMA_MATCH="${TRADE_BEHAVIOR_ROLLBACK_REQUIRE_SCHEMA_MATCH:-1}"
export REPLAY_ABLATION_REQUIRE_MODEL_FEATURE_NAMES="${REPLAY_ABLATION_REQUIRE_MODEL_FEATURE_NAMES:-1}"
export REPLAY_ABLATION_REQUIRE_FULL_DIM_MATCH="${REPLAY_ABLATION_REQUIRE_FULL_DIM_MATCH:-1}"

"$PYTHON_BIN" "$PROJECT_ROOT/scripts/weekly_retrain.py" \
  --continue-on-error \
  --active-only \
  --max-targets 12 \
  --min-model-age-hours 18

echo "daily_small_retrain complete utc=$STAMP"
