#!/bin/zsh
set -euo pipefail

ROOT="/Users/dankingsley/PycharmProjects/schwab_trading_bot"
PY="$ROOT/.venv312/bin/python"

if [[ ! -x "$PY" ]]; then
  echo "missing python: $PY" >&2
  exit 2
fi

cd "$ROOT"

# Safety defaults for focused live-data monitoring.
export MARKET_DATA_ONLY="${MARKET_DATA_ONLY:-1}"
export ALLOW_ORDER_EXECUTION="${ALLOW_ORDER_EXECUTION:-0}"
export ENABLE_RESOURCE_GUARD="${ENABLE_RESOURCE_GUARD:-0}"

# Focus universe: NVDA post-earnings plus high-correlation semiconductor names.
export SHADOW_SYMBOLS_CORE="${SHADOW_SYMBOLS_CORE:-NVDA,QQQ,SOXX,SPY,AMD,AVGO,MSFT,AAPL}"
export SHADOW_SYMBOLS_VOLATILE="${SHADOW_SYMBOLS_VOLATILE:-SOXL,SOXS,SMCI,MU,TSM,TSLA,MSTR,COIN}"
export SHADOW_SYMBOLS_DEFENSIVE="${SHADOW_SYMBOLS_DEFENSIVE:-TLT,GLD,UUP,VIXY,IEF,SHY}"
export SHADOW_SYMBOLS_COMMOD_FX_INTL="${SHADOW_SYMBOLS_COMMOD_FX_INTL:-}"
export DIVIDEND_SYMBOLS="${DIVIDEND_SYMBOLS:-SCHD,VIG,DGRO,JNJ,PG,KO,PEP,XOM,CVX,O,MAIN}"
export BOND_SYMBOLS="${BOND_SYMBOLS:-TLT,IEF,SHY,TLH,TIP,LQD,HYG,JNK,BND,AGG}"

# Higher sampling on core/volatile symbols during the morning reaction window.
export SHADOW_LOOP_INTERVAL="${SHADOW_LOOP_INTERVAL:-6}"
export CORE_SYMBOL_EVERY_N_ITERS="${CORE_SYMBOL_EVERY_N_ITERS:-1}"
export VOLATILE_SYMBOL_EVERY_N_ITERS="${VOLATILE_SYMBOL_EVERY_N_ITERS:-1}"
export DEFENSIVE_SYMBOL_EVERY_N_ITERS="${DEFENSIVE_SYMBOL_EVERY_N_ITERS:-3}"
export SLEEVE_WORKERS_BASELINE="${SLEEVE_WORKERS_BASELINE:-6}"
export SLEEVE_WORKERS_AGGRESSIVE="${SLEEVE_WORKERS_AGGRESSIVE:-5}"

# Keep guardrails active while narrowing lock windows around open.
export EVENT_LOCK_ENABLED="${EVENT_LOCK_ENABLED:-1}"
export EVENT_LOCK_WINDOWS_ET="${EVENT_LOCK_WINDOWS_ET:-09:29-09:33,09:59-10:03}"
export PREOPEN_REPLAY_SANITY_ENABLED="${PREOPEN_REPLAY_SANITY_ENABLED:-1}"
export FEATURE_FRESHNESS_GUARD_ENABLED="${FEATURE_FRESHNESS_GUARD_ENABLED:-1}"
export FEATURE_FRESHNESS_MAX_AGE_SECONDS="${FEATURE_FRESHNESS_MAX_AGE_SECONDS:-12}"
export MASTER_LATENCY_SLO_GUARD_ENABLED="${MASTER_LATENCY_SLO_GUARD_ENABLED:-1}"
export MASTER_LATENCY_SLO_TIMEOUT_MS="${MASTER_LATENCY_SLO_TIMEOUT_MS:-800}"
export CANARY_MAX_WEIGHT="${CANARY_MAX_WEIGHT:-0.05}"

exec "$PY" scripts/run_all_sleeves.py --with-aggressive-modes \
  --symbols-core "$SHADOW_SYMBOLS_CORE" \
  --symbols-volatile "$SHADOW_SYMBOLS_VOLATILE" \
  --symbols-defensive "$SHADOW_SYMBOLS_DEFENSIVE${SHADOW_SYMBOLS_COMMOD_FX_INTL:+,$SHADOW_SYMBOLS_COMMOD_FX_INTL}" \
  --dividend-symbols "$DIVIDEND_SYMBOLS" \
  --bond-symbols "$BOND_SYMBOLS" \
  "$@"
